// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: loadline/v1/arena.proto

package loadlinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kekubhai/Loadline/apps/simulator/loadline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArenaServiceName is the fully-qualified name of the ArenaService service.
	ArenaServiceName = "loadline.v1.ArenaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArenaServiceListChallengesProcedure is the fully-qualified name of the ArenaService's
	// ListChallenges RPC.
	ArenaServiceListChallengesProcedure = "/loadline.v1.ArenaService/ListChallenges"
	// ArenaServiceGetChallengeProcedure is the fully-qualified name of the ArenaService's GetChallenge
	// RPC.
	ArenaServiceGetChallengeProcedure = "/loadline.v1.ArenaService/GetChallenge"
	// ArenaServiceSubmitChallengeProcedure is the fully-qualified name of the ArenaService's
	// SubmitChallenge RPC.
	ArenaServiceSubmitChallengeProcedure = "/loadline.v1.ArenaService/SubmitChallenge"
	// ArenaServiceGetChallengeSubmissionProcedure is the fully-qualified name of the ArenaService's
	// GetChallengeSubmission RPC.
	ArenaServiceGetChallengeSubmissionProcedure = "/loadline.v1.ArenaService/GetChallengeSubmission"
	// ArenaServiceGetChallengeLeaderboardProcedure is the fully-qualified name of the ArenaService's
	// GetChallengeLeaderboard RPC.
	ArenaServiceGetChallengeLeaderboardProcedure = "/loadline.v1.ArenaService/GetChallengeLeaderboard"
)

// ArenaServiceClient is a client for the loadline.v1.ArenaService service.
type ArenaServiceClient interface {
	// List every embedded challenge.
	ListChallenges(context.Context, *connect.Request[v1.ListChallengesRequest]) (*connect.Response[v1.ListChallengesResponse], error)
	// Fetch one challenge with its full evaluation rules.
	GetChallenge(context.Context, *connect.Request[v1.GetChallengeRequest]) (*connect.Response[v1.GetChallengeResponse], error)
	// Benchmark a stored architecture version against a challenge.
	SubmitChallenge(context.Context, *connect.Request[v1.SubmitChallengeRequest]) (*connect.Response[v1.SubmitChallengeResponse], error)
	// Fetch one submission by id.
	GetChallengeSubmission(context.Context, *connect.Request[v1.GetChallengeSubmissionRequest]) (*connect.Response[v1.GetChallengeSubmissionResponse], error)
	// Fetch a challenge's leaderboard (score-ranked, or most recent).
	GetChallengeLeaderboard(context.Context, *connect.Request[v1.GetChallengeLeaderboardRequest]) (*connect.Response[v1.GetChallengeLeaderboardResponse], error)
}

// NewArenaServiceClient constructs a client for the loadline.v1.ArenaService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArenaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArenaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	arenaServiceMethods := v1.File_loadline_v1_arena_proto.Services().ByName("ArenaService").Methods()
	return &arenaServiceClient{
		listChallenges: connect.NewClient[v1.ListChallengesRequest, v1.ListChallengesResponse](
			httpClient,
			baseURL+ArenaServiceListChallengesProcedure,
			connect.WithSchema(arenaServiceMethods.ByName("ListChallenges")),
			connect.WithClientOptions(opts...),
		),
		getChallenge: connect.NewClient[v1.GetChallengeRequest, v1.GetChallengeResponse](
			httpClient,
			baseURL+ArenaServiceGetChallengeProcedure,
			connect.WithSchema(arenaServiceMethods.ByName("GetChallenge")),
			connect.WithClientOptions(opts...),
		),
		submitChallenge: connect.NewClient[v1.SubmitChallengeRequest, v1.SubmitChallengeResponse](
			httpClient,
			baseURL+ArenaServiceSubmitChallengeProcedure,
			connect.WithSchema(arenaServiceMethods.ByName("SubmitChallenge")),
			connect.WithClientOptions(opts...),
		),
		getChallengeSubmission: connect.NewClient[v1.GetChallengeSubmissionRequest, v1.GetChallengeSubmissionResponse](
			httpClient,
			baseURL+ArenaServiceGetChallengeSubmissionProcedure,
			connect.WithSchema(arenaServiceMethods.ByName("GetChallengeSubmission")),
			connect.WithClientOptions(opts...),
		),
		getChallengeLeaderboard: connect.NewClient[v1.GetChallengeLeaderboardRequest, v1.GetChallengeLeaderboardResponse](
			httpClient,
			baseURL+ArenaServiceGetChallengeLeaderboardProcedure,
			connect.WithSchema(arenaServiceMethods.ByName("GetChallengeLeaderboard")),
			connect.WithClientOptions(opts...),
		),
	}
}

// arenaServiceClient implements ArenaServiceClient.
type arenaServiceClient struct {
	listChallenges          *connect.Client[v1.ListChallengesRequest, v1.ListChallengesResponse]
	getChallenge            *connect.Client[v1.GetChallengeRequest, v1.GetChallengeResponse]
	submitChallenge         *connect.Client[v1.SubmitChallengeRequest, v1.SubmitChallengeResponse]
	getChallengeSubmission  *connect.Client[v1.GetChallengeSubmissionRequest, v1.GetChallengeSubmissionResponse]
	getChallengeLeaderboard *connect.Client[v1.GetChallengeLeaderboardRequest, v1.GetChallengeLeaderboardResponse]
}

// ListChallenges calls loadline.v1.ArenaService.ListChallenges.
func (c *arenaServiceClient) ListChallenges(ctx context.Context, req *connect.Request[v1.ListChallengesRequest]) (*connect.Response[v1.ListChallengesResponse], error) {
	return c.listChallenges.CallUnary(ctx, req)
}

// GetChallenge calls loadline.v1.ArenaService.GetChallenge.
func (c *arenaServiceClient) GetChallenge(ctx context.Context, req *connect.Request[v1.GetChallengeRequest]) (*connect.Response[v1.GetChallengeResponse], error) {
	return c.getChallenge.CallUnary(ctx, req)
}

// SubmitChallenge calls loadline.v1.ArenaService.SubmitChallenge.
func (c *arenaServiceClient) SubmitChallenge(ctx context.Context, req *connect.Request[v1.SubmitChallengeRequest]) (*connect.Response[v1.SubmitChallengeResponse], error) {
	return c.submitChallenge.CallUnary(ctx, req)
}

// GetChallengeSubmission calls loadline.v1.ArenaService.GetChallengeSubmission.
func (c *arenaServiceClient) GetChallengeSubmission(ctx context.Context, req *connect.Request[v1.GetChallengeSubmissionRequest]) (*connect.Response[v1.GetChallengeSubmissionResponse], error) {
	return c.getChallengeSubmission.CallUnary(ctx, req)
}

// GetChallengeLeaderboard calls loadline.v1.ArenaService.GetChallengeLeaderboard.
func (c *arenaServiceClient) GetChallengeLeaderboard(ctx context.Context, req *connect.Request[v1.GetChallengeLeaderboardRequest]) (*connect.Response[v1.GetChallengeLeaderboardResponse], error) {
	return c.getChallengeLeaderboard.CallUnary(ctx, req)
}

// ArenaServiceHandler is an implementation of the loadline.v1.ArenaService service.
type ArenaServiceHandler interface {
	// List every embedded challenge.
	ListChallenges(context.Context, *connect.Request[v1.ListChallengesRequest]) (*connect.Response[v1.ListChallengesResponse], error)
	// Fetch one challenge with its full evaluation rules.
	GetChallenge(context.Context, *connect.Request[v1.GetChallengeRequest]) (*connect.Response[v1.GetChallengeResponse], error)
	// Benchmark a stored architecture version against a challenge.
	SubmitChallenge(context.Context, *connect.Request[v1.SubmitChallengeRequest]) (*connect.Response[v1.SubmitChallengeResponse], error)
	// Fetch one submission by id.
	GetChallengeSubmission(context.Context, *connect.Request[v1.GetChallengeSubmissionRequest]) (*connect.Response[v1.GetChallengeSubmissionResponse], error)
	// Fetch a challenge's leaderboard (score-ranked, or most recent).
	GetChallengeLeaderboard(context.Context, *connect.Request[v1.GetChallengeLeaderboardRequest]) (*connect.Response[v1.GetChallengeLeaderboardResponse], error)
}

// NewArenaServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArenaServiceHandler(svc ArenaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	arenaServiceMethods := v1.File_loadline_v1_arena_proto.Services().ByName("ArenaService").Methods()
	arenaServiceListChallengesHandler := connect.NewUnaryHandler(
		ArenaServiceListChallengesProcedure,
		svc.ListChallenges,
		connect.WithSchema(arenaServiceMethods.ByName("ListChallenges")),
		connect.WithHandlerOptions(opts...),
	)
	arenaServiceGetChallengeHandler := connect.NewUnaryHandler(
		ArenaServiceGetChallengeProcedure,
		svc.GetChallenge,
		connect.WithSchema(arenaServiceMethods.ByName("GetChallenge")),
		connect.WithHandlerOptions(opts...),
	)
	arenaServiceSubmitChallengeHandler := connect.NewUnaryHandler(
		ArenaServiceSubmitChallengeProcedure,
		svc.SubmitChallenge,
		connect.WithSchema(arenaServiceMethods.ByName("SubmitChallenge")),
		connect.WithHandlerOptions(opts...),
	)
	arenaServiceGetChallengeSubmissionHandler := connect.NewUnaryHandler(
		ArenaServiceGetChallengeSubmissionProcedure,
		svc.GetChallengeSubmission,
		connect.WithSchema(arenaServiceMethods.ByName("GetChallengeSubmission")),
		connect.WithHandlerOptions(opts...),
	)
	arenaServiceGetChallengeLeaderboardHandler := connect.NewUnaryHandler(
		ArenaServiceGetChallengeLeaderboardProcedure,
		svc.GetChallengeLeaderboard,
		connect.WithSchema(arenaServiceMethods.ByName("GetChallengeLeaderboard")),
		connect.WithHandlerOptions(opts...),
	)
	return "/loadline.v1.ArenaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArenaServiceListChallengesProcedure:
			arenaServiceListChallengesHandler.ServeHTTP(w, r)
		case ArenaServiceGetChallengeProcedure:
			arenaServiceGetChallengeHandler.ServeHTTP(w, r)
		case ArenaServiceSubmitChallengeProcedure:
			arenaServiceSubmitChallengeHandler.ServeHTTP(w, r)
		case ArenaServiceGetChallengeSubmissionProcedure:
			arenaServiceGetChallengeSubmissionHandler.ServeHTTP(w, r)
		case ArenaServiceGetChallengeLeaderboardProcedure:
			arenaServiceGetChallengeLeaderboardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArenaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArenaServiceHandler struct{}

func (UnimplementedArenaServiceHandler) ListChallenges(context.Context, *connect.Request[v1.ListChallengesRequest]) (*connect.Response[v1.ListChallengesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.ArenaService.ListChallenges is not implemented"))
}

func (UnimplementedArenaServiceHandler) GetChallenge(context.Context, *connect.Request[v1.GetChallengeRequest]) (*connect.Response[v1.GetChallengeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.ArenaService.GetChallenge is not implemented"))
}

func (UnimplementedArenaServiceHandler) SubmitChallenge(context.Context, *connect.Request[v1.SubmitChallengeRequest]) (*connect.Response[v1.SubmitChallengeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.ArenaService.SubmitChallenge is not implemented"))
}

func (UnimplementedArenaServiceHandler) GetChallengeSubmission(context.Context, *connect.Request[v1.GetChallengeSubmissionRequest]) (*connect.Response[v1.GetChallengeSubmissionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.ArenaService.GetChallengeSubmission is not implemented"))
}

func (UnimplementedArenaServiceHandler) GetChallengeLeaderboard(context.Context, *connect.Request[v1.GetChallengeLeaderboardRequest]) (*connect.Response[v1.GetChallengeLeaderboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.ArenaService.GetChallengeLeaderboard is not implemented"))
}
