// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: loadline/v1/simulation.proto

package loadlinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kekubhai/Loadline/apps/simulator/loadline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SimulationServiceName is the fully-qualified name of the SimulationService service.
	SimulationServiceName = "loadline.v1.SimulationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SimulationServiceCreateSimulationProcedure is the fully-qualified name of the SimulationService's
	// CreateSimulation RPC.
	SimulationServiceCreateSimulationProcedure = "/loadline.v1.SimulationService/CreateSimulation"
	// SimulationServiceRunSimulationProcedure is the fully-qualified name of the SimulationService's
	// RunSimulation RPC.
	SimulationServiceRunSimulationProcedure = "/loadline.v1.SimulationService/RunSimulation"
	// SimulationServiceGetSimulationStatusProcedure is the fully-qualified name of the
	// SimulationService's GetSimulationStatus RPC.
	SimulationServiceGetSimulationStatusProcedure = "/loadline.v1.SimulationService/GetSimulationStatus"
	// SimulationServiceStreamMetricsProcedure is the fully-qualified name of the SimulationService's
	// StreamMetrics RPC.
	SimulationServiceStreamMetricsProcedure = "/loadline.v1.SimulationService/StreamMetrics"
	// SimulationServicePauseSimulationProcedure is the fully-qualified name of the SimulationService's
	// PauseSimulation RPC.
	SimulationServicePauseSimulationProcedure = "/loadline.v1.SimulationService/PauseSimulation"
	// SimulationServiceResumeSimulationProcedure is the fully-qualified name of the SimulationService's
	// ResumeSimulation RPC.
	SimulationServiceResumeSimulationProcedure = "/loadline.v1.SimulationService/ResumeSimulation"
	// SimulationServiceStopSimulationProcedure is the fully-qualified name of the SimulationService's
	// StopSimulation RPC.
	SimulationServiceStopSimulationProcedure = "/loadline.v1.SimulationService/StopSimulation"
	// SimulationServiceSetWallDurationProcedure is the fully-qualified name of the SimulationService's
	// SetWallDuration RPC.
	SimulationServiceSetWallDurationProcedure = "/loadline.v1.SimulationService/SetWallDuration"
	// SimulationServiceGetResultsProcedure is the fully-qualified name of the SimulationService's
	// GetResults RPC.
	SimulationServiceGetResultsProcedure = "/loadline.v1.SimulationService/GetResults"
	// SimulationServiceGetDiagnosisProcedure is the fully-qualified name of the SimulationService's
	// GetDiagnosis RPC.
	SimulationServiceGetDiagnosisProcedure = "/loadline.v1.SimulationService/GetDiagnosis"
	// SimulationServiceGetCapacityProcedure is the fully-qualified name of the SimulationService's
	// GetCapacity RPC.
	SimulationServiceGetCapacityProcedure = "/loadline.v1.SimulationService/GetCapacity"
	// SimulationServiceGetCostEstimateProcedure is the fully-qualified name of the SimulationService's
	// GetCostEstimate RPC.
	SimulationServiceGetCostEstimateProcedure = "/loadline.v1.SimulationService/GetCostEstimate"
	// SimulationServiceListCatalogProcedure is the fully-qualified name of the SimulationService's
	// ListCatalog RPC.
	SimulationServiceListCatalogProcedure = "/loadline.v1.SimulationService/ListCatalog"
)

// SimulationServiceClient is a client for the loadline.v1.SimulationService service.
type SimulationServiceClient interface {
	// Create a stored simulation (architecture + workload + options).
	CreateSimulation(context.Context, *connect.Request[v1.CreateSimulationRequest]) (*connect.Response[v1.CreateSimulationResponse], error)
	// Start asynchronous execution of a stored simulation.
	RunSimulation(context.Context, *connect.Request[v1.RunSimulationRequest]) (*connect.Response[v1.RunSimulationResponse], error)
	// Poll a simulation's status and latest progress snapshot.
	GetSimulationStatus(context.Context, *connect.Request[v1.GetSimulationStatusRequest]) (*connect.Response[v1.GetSimulationStatusResponse], error)
	// Stream progress snapshots while running, then status and final
	// results; the stream ends after the terminal frame. Control
	// transitions (pause/resume/stop) are also broadcast on this stream.
	StreamMetrics(context.Context, *connect.Request[v1.StreamMetricsRequest]) (*connect.ServerStreamForClient[v1.StreamMetricsResponse], error)
	// Pause a RUNNING simulation at the current simulated instant. The
	// engine finishes the in-flight event, then idles without advancing
	// simulated time. Final metrics remain available on completion.
	PauseSimulation(context.Context, *connect.Request[v1.PauseSimulationRequest]) (*connect.Response[v1.PauseSimulationResponse], error)
	// Resume a PAUSED simulation, optionally re-targeting the wall-clock
	// pacing in the same call.
	ResumeSimulation(context.Context, *connect.Request[v1.ResumeSimulationRequest]) (*connect.Response[v1.ResumeSimulationResponse], error)
	// Stop a RUNNING or PAUSED simulation before its horizon. The engine
	// drains the in-flight event and publishes partial results (marked
	// stopped, not completed); they stay queryable.
	StopSimulation(context.Context, *connect.Request[v1.StopSimulationRequest]) (*connect.Response[v1.StopSimulationResponse], error)
	// SetWallDuration re-targets the wall-clock pacing of a live run
	// without pausing it. 0 restores the default 1s-of-sim-per-second.
	SetWallDuration(context.Context, *connect.Request[v1.SetWallDurationRequest]) (*connect.Response[v1.SetWallDurationResponse], error)
	// Fetch final results of a completed run.
	GetResults(context.Context, *connect.Request[v1.GetResultsRequest]) (*connect.Response[v1.GetResultsResponse], error)
	// Fetch the bottleneck diagnosis (optionally vs a baseline run).
	GetDiagnosis(context.Context, *connect.Request[v1.GetDiagnosisRequest]) (*connect.Response[v1.GetDiagnosisResponse], error)
	// Fetch per-component capacity estimates.
	GetCapacity(context.Context, *connect.Request[v1.GetCapacityRequest]) (*connect.Response[v1.GetCapacityResponse], error)
	// Fetch the monthly cost estimate (ESTIMATE, not live billing).
	GetCostEstimate(context.Context, *connect.Request[v1.GetCostEstimateRequest]) (*connect.Response[v1.GetCostEstimateResponse], error)
	// List the built-in provider catalog.
	ListCatalog(context.Context, *connect.Request[v1.ListCatalogRequest]) (*connect.Response[v1.ListCatalogResponse], error)
}

// NewSimulationServiceClient constructs a client for the loadline.v1.SimulationService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSimulationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SimulationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	simulationServiceMethods := v1.File_loadline_v1_simulation_proto.Services().ByName("SimulationService").Methods()
	return &simulationServiceClient{
		createSimulation: connect.NewClient[v1.CreateSimulationRequest, v1.CreateSimulationResponse](
			httpClient,
			baseURL+SimulationServiceCreateSimulationProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("CreateSimulation")),
			connect.WithClientOptions(opts...),
		),
		runSimulation: connect.NewClient[v1.RunSimulationRequest, v1.RunSimulationResponse](
			httpClient,
			baseURL+SimulationServiceRunSimulationProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("RunSimulation")),
			connect.WithClientOptions(opts...),
		),
		getSimulationStatus: connect.NewClient[v1.GetSimulationStatusRequest, v1.GetSimulationStatusResponse](
			httpClient,
			baseURL+SimulationServiceGetSimulationStatusProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("GetSimulationStatus")),
			connect.WithClientOptions(opts...),
		),
		streamMetrics: connect.NewClient[v1.StreamMetricsRequest, v1.StreamMetricsResponse](
			httpClient,
			baseURL+SimulationServiceStreamMetricsProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("StreamMetrics")),
			connect.WithClientOptions(opts...),
		),
		pauseSimulation: connect.NewClient[v1.PauseSimulationRequest, v1.PauseSimulationResponse](
			httpClient,
			baseURL+SimulationServicePauseSimulationProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("PauseSimulation")),
			connect.WithClientOptions(opts...),
		),
		resumeSimulation: connect.NewClient[v1.ResumeSimulationRequest, v1.ResumeSimulationResponse](
			httpClient,
			baseURL+SimulationServiceResumeSimulationProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("ResumeSimulation")),
			connect.WithClientOptions(opts...),
		),
		stopSimulation: connect.NewClient[v1.StopSimulationRequest, v1.StopSimulationResponse](
			httpClient,
			baseURL+SimulationServiceStopSimulationProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("StopSimulation")),
			connect.WithClientOptions(opts...),
		),
		setWallDuration: connect.NewClient[v1.SetWallDurationRequest, v1.SetWallDurationResponse](
			httpClient,
			baseURL+SimulationServiceSetWallDurationProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("SetWallDuration")),
			connect.WithClientOptions(opts...),
		),
		getResults: connect.NewClient[v1.GetResultsRequest, v1.GetResultsResponse](
			httpClient,
			baseURL+SimulationServiceGetResultsProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("GetResults")),
			connect.WithClientOptions(opts...),
		),
		getDiagnosis: connect.NewClient[v1.GetDiagnosisRequest, v1.GetDiagnosisResponse](
			httpClient,
			baseURL+SimulationServiceGetDiagnosisProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("GetDiagnosis")),
			connect.WithClientOptions(opts...),
		),
		getCapacity: connect.NewClient[v1.GetCapacityRequest, v1.GetCapacityResponse](
			httpClient,
			baseURL+SimulationServiceGetCapacityProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("GetCapacity")),
			connect.WithClientOptions(opts...),
		),
		getCostEstimate: connect.NewClient[v1.GetCostEstimateRequest, v1.GetCostEstimateResponse](
			httpClient,
			baseURL+SimulationServiceGetCostEstimateProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("GetCostEstimate")),
			connect.WithClientOptions(opts...),
		),
		listCatalog: connect.NewClient[v1.ListCatalogRequest, v1.ListCatalogResponse](
			httpClient,
			baseURL+SimulationServiceListCatalogProcedure,
			connect.WithSchema(simulationServiceMethods.ByName("ListCatalog")),
			connect.WithClientOptions(opts...),
		),
	}
}

// simulationServiceClient implements SimulationServiceClient.
type simulationServiceClient struct {
	createSimulation    *connect.Client[v1.CreateSimulationRequest, v1.CreateSimulationResponse]
	runSimulation       *connect.Client[v1.RunSimulationRequest, v1.RunSimulationResponse]
	getSimulationStatus *connect.Client[v1.GetSimulationStatusRequest, v1.GetSimulationStatusResponse]
	streamMetrics       *connect.Client[v1.StreamMetricsRequest, v1.StreamMetricsResponse]
	pauseSimulation     *connect.Client[v1.PauseSimulationRequest, v1.PauseSimulationResponse]
	resumeSimulation    *connect.Client[v1.ResumeSimulationRequest, v1.ResumeSimulationResponse]
	stopSimulation      *connect.Client[v1.StopSimulationRequest, v1.StopSimulationResponse]
	setWallDuration     *connect.Client[v1.SetWallDurationRequest, v1.SetWallDurationResponse]
	getResults          *connect.Client[v1.GetResultsRequest, v1.GetResultsResponse]
	getDiagnosis        *connect.Client[v1.GetDiagnosisRequest, v1.GetDiagnosisResponse]
	getCapacity         *connect.Client[v1.GetCapacityRequest, v1.GetCapacityResponse]
	getCostEstimate     *connect.Client[v1.GetCostEstimateRequest, v1.GetCostEstimateResponse]
	listCatalog         *connect.Client[v1.ListCatalogRequest, v1.ListCatalogResponse]
}

// CreateSimulation calls loadline.v1.SimulationService.CreateSimulation.
func (c *simulationServiceClient) CreateSimulation(ctx context.Context, req *connect.Request[v1.CreateSimulationRequest]) (*connect.Response[v1.CreateSimulationResponse], error) {
	return c.createSimulation.CallUnary(ctx, req)
}

// RunSimulation calls loadline.v1.SimulationService.RunSimulation.
func (c *simulationServiceClient) RunSimulation(ctx context.Context, req *connect.Request[v1.RunSimulationRequest]) (*connect.Response[v1.RunSimulationResponse], error) {
	return c.runSimulation.CallUnary(ctx, req)
}

// GetSimulationStatus calls loadline.v1.SimulationService.GetSimulationStatus.
func (c *simulationServiceClient) GetSimulationStatus(ctx context.Context, req *connect.Request[v1.GetSimulationStatusRequest]) (*connect.Response[v1.GetSimulationStatusResponse], error) {
	return c.getSimulationStatus.CallUnary(ctx, req)
}

// StreamMetrics calls loadline.v1.SimulationService.StreamMetrics.
func (c *simulationServiceClient) StreamMetrics(ctx context.Context, req *connect.Request[v1.StreamMetricsRequest]) (*connect.ServerStreamForClient[v1.StreamMetricsResponse], error) {
	return c.streamMetrics.CallServerStream(ctx, req)
}

// PauseSimulation calls loadline.v1.SimulationService.PauseSimulation.
func (c *simulationServiceClient) PauseSimulation(ctx context.Context, req *connect.Request[v1.PauseSimulationRequest]) (*connect.Response[v1.PauseSimulationResponse], error) {
	return c.pauseSimulation.CallUnary(ctx, req)
}

// ResumeSimulation calls loadline.v1.SimulationService.ResumeSimulation.
func (c *simulationServiceClient) ResumeSimulation(ctx context.Context, req *connect.Request[v1.ResumeSimulationRequest]) (*connect.Response[v1.ResumeSimulationResponse], error) {
	return c.resumeSimulation.CallUnary(ctx, req)
}

// StopSimulation calls loadline.v1.SimulationService.StopSimulation.
func (c *simulationServiceClient) StopSimulation(ctx context.Context, req *connect.Request[v1.StopSimulationRequest]) (*connect.Response[v1.StopSimulationResponse], error) {
	return c.stopSimulation.CallUnary(ctx, req)
}

// SetWallDuration calls loadline.v1.SimulationService.SetWallDuration.
func (c *simulationServiceClient) SetWallDuration(ctx context.Context, req *connect.Request[v1.SetWallDurationRequest]) (*connect.Response[v1.SetWallDurationResponse], error) {
	return c.setWallDuration.CallUnary(ctx, req)
}

// GetResults calls loadline.v1.SimulationService.GetResults.
func (c *simulationServiceClient) GetResults(ctx context.Context, req *connect.Request[v1.GetResultsRequest]) (*connect.Response[v1.GetResultsResponse], error) {
	return c.getResults.CallUnary(ctx, req)
}

// GetDiagnosis calls loadline.v1.SimulationService.GetDiagnosis.
func (c *simulationServiceClient) GetDiagnosis(ctx context.Context, req *connect.Request[v1.GetDiagnosisRequest]) (*connect.Response[v1.GetDiagnosisResponse], error) {
	return c.getDiagnosis.CallUnary(ctx, req)
}

// GetCapacity calls loadline.v1.SimulationService.GetCapacity.
func (c *simulationServiceClient) GetCapacity(ctx context.Context, req *connect.Request[v1.GetCapacityRequest]) (*connect.Response[v1.GetCapacityResponse], error) {
	return c.getCapacity.CallUnary(ctx, req)
}

// GetCostEstimate calls loadline.v1.SimulationService.GetCostEstimate.
func (c *simulationServiceClient) GetCostEstimate(ctx context.Context, req *connect.Request[v1.GetCostEstimateRequest]) (*connect.Response[v1.GetCostEstimateResponse], error) {
	return c.getCostEstimate.CallUnary(ctx, req)
}

// ListCatalog calls loadline.v1.SimulationService.ListCatalog.
func (c *simulationServiceClient) ListCatalog(ctx context.Context, req *connect.Request[v1.ListCatalogRequest]) (*connect.Response[v1.ListCatalogResponse], error) {
	return c.listCatalog.CallUnary(ctx, req)
}

// SimulationServiceHandler is an implementation of the loadline.v1.SimulationService service.
type SimulationServiceHandler interface {
	// Create a stored simulation (architecture + workload + options).
	CreateSimulation(context.Context, *connect.Request[v1.CreateSimulationRequest]) (*connect.Response[v1.CreateSimulationResponse], error)
	// Start asynchronous execution of a stored simulation.
	RunSimulation(context.Context, *connect.Request[v1.RunSimulationRequest]) (*connect.Response[v1.RunSimulationResponse], error)
	// Poll a simulation's status and latest progress snapshot.
	GetSimulationStatus(context.Context, *connect.Request[v1.GetSimulationStatusRequest]) (*connect.Response[v1.GetSimulationStatusResponse], error)
	// Stream progress snapshots while running, then status and final
	// results; the stream ends after the terminal frame. Control
	// transitions (pause/resume/stop) are also broadcast on this stream.
	StreamMetrics(context.Context, *connect.Request[v1.StreamMetricsRequest], *connect.ServerStream[v1.StreamMetricsResponse]) error
	// Pause a RUNNING simulation at the current simulated instant. The
	// engine finishes the in-flight event, then idles without advancing
	// simulated time. Final metrics remain available on completion.
	PauseSimulation(context.Context, *connect.Request[v1.PauseSimulationRequest]) (*connect.Response[v1.PauseSimulationResponse], error)
	// Resume a PAUSED simulation, optionally re-targeting the wall-clock
	// pacing in the same call.
	ResumeSimulation(context.Context, *connect.Request[v1.ResumeSimulationRequest]) (*connect.Response[v1.ResumeSimulationResponse], error)
	// Stop a RUNNING or PAUSED simulation before its horizon. The engine
	// drains the in-flight event and publishes partial results (marked
	// stopped, not completed); they stay queryable.
	StopSimulation(context.Context, *connect.Request[v1.StopSimulationRequest]) (*connect.Response[v1.StopSimulationResponse], error)
	// SetWallDuration re-targets the wall-clock pacing of a live run
	// without pausing it. 0 restores the default 1s-of-sim-per-second.
	SetWallDuration(context.Context, *connect.Request[v1.SetWallDurationRequest]) (*connect.Response[v1.SetWallDurationResponse], error)
	// Fetch final results of a completed run.
	GetResults(context.Context, *connect.Request[v1.GetResultsRequest]) (*connect.Response[v1.GetResultsResponse], error)
	// Fetch the bottleneck diagnosis (optionally vs a baseline run).
	GetDiagnosis(context.Context, *connect.Request[v1.GetDiagnosisRequest]) (*connect.Response[v1.GetDiagnosisResponse], error)
	// Fetch per-component capacity estimates.
	GetCapacity(context.Context, *connect.Request[v1.GetCapacityRequest]) (*connect.Response[v1.GetCapacityResponse], error)
	// Fetch the monthly cost estimate (ESTIMATE, not live billing).
	GetCostEstimate(context.Context, *connect.Request[v1.GetCostEstimateRequest]) (*connect.Response[v1.GetCostEstimateResponse], error)
	// List the built-in provider catalog.
	ListCatalog(context.Context, *connect.Request[v1.ListCatalogRequest]) (*connect.Response[v1.ListCatalogResponse], error)
}

// NewSimulationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSimulationServiceHandler(svc SimulationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	simulationServiceMethods := v1.File_loadline_v1_simulation_proto.Services().ByName("SimulationService").Methods()
	simulationServiceCreateSimulationHandler := connect.NewUnaryHandler(
		SimulationServiceCreateSimulationProcedure,
		svc.CreateSimulation,
		connect.WithSchema(simulationServiceMethods.ByName("CreateSimulation")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceRunSimulationHandler := connect.NewUnaryHandler(
		SimulationServiceRunSimulationProcedure,
		svc.RunSimulation,
		connect.WithSchema(simulationServiceMethods.ByName("RunSimulation")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceGetSimulationStatusHandler := connect.NewUnaryHandler(
		SimulationServiceGetSimulationStatusProcedure,
		svc.GetSimulationStatus,
		connect.WithSchema(simulationServiceMethods.ByName("GetSimulationStatus")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceStreamMetricsHandler := connect.NewServerStreamHandler(
		SimulationServiceStreamMetricsProcedure,
		svc.StreamMetrics,
		connect.WithSchema(simulationServiceMethods.ByName("StreamMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServicePauseSimulationHandler := connect.NewUnaryHandler(
		SimulationServicePauseSimulationProcedure,
		svc.PauseSimulation,
		connect.WithSchema(simulationServiceMethods.ByName("PauseSimulation")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceResumeSimulationHandler := connect.NewUnaryHandler(
		SimulationServiceResumeSimulationProcedure,
		svc.ResumeSimulation,
		connect.WithSchema(simulationServiceMethods.ByName("ResumeSimulation")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceStopSimulationHandler := connect.NewUnaryHandler(
		SimulationServiceStopSimulationProcedure,
		svc.StopSimulation,
		connect.WithSchema(simulationServiceMethods.ByName("StopSimulation")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceSetWallDurationHandler := connect.NewUnaryHandler(
		SimulationServiceSetWallDurationProcedure,
		svc.SetWallDuration,
		connect.WithSchema(simulationServiceMethods.ByName("SetWallDuration")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceGetResultsHandler := connect.NewUnaryHandler(
		SimulationServiceGetResultsProcedure,
		svc.GetResults,
		connect.WithSchema(simulationServiceMethods.ByName("GetResults")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceGetDiagnosisHandler := connect.NewUnaryHandler(
		SimulationServiceGetDiagnosisProcedure,
		svc.GetDiagnosis,
		connect.WithSchema(simulationServiceMethods.ByName("GetDiagnosis")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceGetCapacityHandler := connect.NewUnaryHandler(
		SimulationServiceGetCapacityProcedure,
		svc.GetCapacity,
		connect.WithSchema(simulationServiceMethods.ByName("GetCapacity")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceGetCostEstimateHandler := connect.NewUnaryHandler(
		SimulationServiceGetCostEstimateProcedure,
		svc.GetCostEstimate,
		connect.WithSchema(simulationServiceMethods.ByName("GetCostEstimate")),
		connect.WithHandlerOptions(opts...),
	)
	simulationServiceListCatalogHandler := connect.NewUnaryHandler(
		SimulationServiceListCatalogProcedure,
		svc.ListCatalog,
		connect.WithSchema(simulationServiceMethods.ByName("ListCatalog")),
		connect.WithHandlerOptions(opts...),
	)
	return "/loadline.v1.SimulationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SimulationServiceCreateSimulationProcedure:
			simulationServiceCreateSimulationHandler.ServeHTTP(w, r)
		case SimulationServiceRunSimulationProcedure:
			simulationServiceRunSimulationHandler.ServeHTTP(w, r)
		case SimulationServiceGetSimulationStatusProcedure:
			simulationServiceGetSimulationStatusHandler.ServeHTTP(w, r)
		case SimulationServiceStreamMetricsProcedure:
			simulationServiceStreamMetricsHandler.ServeHTTP(w, r)
		case SimulationServicePauseSimulationProcedure:
			simulationServicePauseSimulationHandler.ServeHTTP(w, r)
		case SimulationServiceResumeSimulationProcedure:
			simulationServiceResumeSimulationHandler.ServeHTTP(w, r)
		case SimulationServiceStopSimulationProcedure:
			simulationServiceStopSimulationHandler.ServeHTTP(w, r)
		case SimulationServiceSetWallDurationProcedure:
			simulationServiceSetWallDurationHandler.ServeHTTP(w, r)
		case SimulationServiceGetResultsProcedure:
			simulationServiceGetResultsHandler.ServeHTTP(w, r)
		case SimulationServiceGetDiagnosisProcedure:
			simulationServiceGetDiagnosisHandler.ServeHTTP(w, r)
		case SimulationServiceGetCapacityProcedure:
			simulationServiceGetCapacityHandler.ServeHTTP(w, r)
		case SimulationServiceGetCostEstimateProcedure:
			simulationServiceGetCostEstimateHandler.ServeHTTP(w, r)
		case SimulationServiceListCatalogProcedure:
			simulationServiceListCatalogHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSimulationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSimulationServiceHandler struct{}

func (UnimplementedSimulationServiceHandler) CreateSimulation(context.Context, *connect.Request[v1.CreateSimulationRequest]) (*connect.Response[v1.CreateSimulationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.CreateSimulation is not implemented"))
}

func (UnimplementedSimulationServiceHandler) RunSimulation(context.Context, *connect.Request[v1.RunSimulationRequest]) (*connect.Response[v1.RunSimulationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.RunSimulation is not implemented"))
}

func (UnimplementedSimulationServiceHandler) GetSimulationStatus(context.Context, *connect.Request[v1.GetSimulationStatusRequest]) (*connect.Response[v1.GetSimulationStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.GetSimulationStatus is not implemented"))
}

func (UnimplementedSimulationServiceHandler) StreamMetrics(context.Context, *connect.Request[v1.StreamMetricsRequest], *connect.ServerStream[v1.StreamMetricsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.StreamMetrics is not implemented"))
}

func (UnimplementedSimulationServiceHandler) PauseSimulation(context.Context, *connect.Request[v1.PauseSimulationRequest]) (*connect.Response[v1.PauseSimulationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.PauseSimulation is not implemented"))
}

func (UnimplementedSimulationServiceHandler) ResumeSimulation(context.Context, *connect.Request[v1.ResumeSimulationRequest]) (*connect.Response[v1.ResumeSimulationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.ResumeSimulation is not implemented"))
}

func (UnimplementedSimulationServiceHandler) StopSimulation(context.Context, *connect.Request[v1.StopSimulationRequest]) (*connect.Response[v1.StopSimulationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.StopSimulation is not implemented"))
}

func (UnimplementedSimulationServiceHandler) SetWallDuration(context.Context, *connect.Request[v1.SetWallDurationRequest]) (*connect.Response[v1.SetWallDurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.SetWallDuration is not implemented"))
}

func (UnimplementedSimulationServiceHandler) GetResults(context.Context, *connect.Request[v1.GetResultsRequest]) (*connect.Response[v1.GetResultsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.GetResults is not implemented"))
}

func (UnimplementedSimulationServiceHandler) GetDiagnosis(context.Context, *connect.Request[v1.GetDiagnosisRequest]) (*connect.Response[v1.GetDiagnosisResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.GetDiagnosis is not implemented"))
}

func (UnimplementedSimulationServiceHandler) GetCapacity(context.Context, *connect.Request[v1.GetCapacityRequest]) (*connect.Response[v1.GetCapacityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.GetCapacity is not implemented"))
}

func (UnimplementedSimulationServiceHandler) GetCostEstimate(context.Context, *connect.Request[v1.GetCostEstimateRequest]) (*connect.Response[v1.GetCostEstimateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.GetCostEstimate is not implemented"))
}

func (UnimplementedSimulationServiceHandler) ListCatalog(context.Context, *connect.Request[v1.ListCatalogRequest]) (*connect.Response[v1.ListCatalogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.SimulationService.ListCatalog is not implemented"))
}
