// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: loadline/v1/workspace.proto

package loadlinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kekubhai/Loadline/apps/simulator/loadline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkspaceServiceName is the fully-qualified name of the WorkspaceService service.
	WorkspaceServiceName = "loadline.v1.WorkspaceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkspaceServiceCreateProjectProcedure is the fully-qualified name of the WorkspaceService's
	// CreateProject RPC.
	WorkspaceServiceCreateProjectProcedure = "/loadline.v1.WorkspaceService/CreateProject"
	// WorkspaceServiceGetProjectProcedure is the fully-qualified name of the WorkspaceService's
	// GetProject RPC.
	WorkspaceServiceGetProjectProcedure = "/loadline.v1.WorkspaceService/GetProject"
	// WorkspaceServiceListProjectsProcedure is the fully-qualified name of the WorkspaceService's
	// ListProjects RPC.
	WorkspaceServiceListProjectsProcedure = "/loadline.v1.WorkspaceService/ListProjects"
	// WorkspaceServiceUpdateProjectProcedure is the fully-qualified name of the WorkspaceService's
	// UpdateProject RPC.
	WorkspaceServiceUpdateProjectProcedure = "/loadline.v1.WorkspaceService/UpdateProject"
	// WorkspaceServiceDeleteProjectProcedure is the fully-qualified name of the WorkspaceService's
	// DeleteProject RPC.
	WorkspaceServiceDeleteProjectProcedure = "/loadline.v1.WorkspaceService/DeleteProject"
	// WorkspaceServiceCreateArchitectureProcedure is the fully-qualified name of the WorkspaceService's
	// CreateArchitecture RPC.
	WorkspaceServiceCreateArchitectureProcedure = "/loadline.v1.WorkspaceService/CreateArchitecture"
	// WorkspaceServiceGetArchitectureProcedure is the fully-qualified name of the WorkspaceService's
	// GetArchitecture RPC.
	WorkspaceServiceGetArchitectureProcedure = "/loadline.v1.WorkspaceService/GetArchitecture"
	// WorkspaceServiceListArchitecturesProcedure is the fully-qualified name of the WorkspaceService's
	// ListArchitectures RPC.
	WorkspaceServiceListArchitecturesProcedure = "/loadline.v1.WorkspaceService/ListArchitectures"
	// WorkspaceServiceUpdateArchitectureProcedure is the fully-qualified name of the WorkspaceService's
	// UpdateArchitecture RPC.
	WorkspaceServiceUpdateArchitectureProcedure = "/loadline.v1.WorkspaceService/UpdateArchitecture"
	// WorkspaceServiceDeleteArchitectureProcedure is the fully-qualified name of the WorkspaceService's
	// DeleteArchitecture RPC.
	WorkspaceServiceDeleteArchitectureProcedure = "/loadline.v1.WorkspaceService/DeleteArchitecture"
	// WorkspaceServiceCreateArchitectureVersionProcedure is the fully-qualified name of the
	// WorkspaceService's CreateArchitectureVersion RPC.
	WorkspaceServiceCreateArchitectureVersionProcedure = "/loadline.v1.WorkspaceService/CreateArchitectureVersion"
	// WorkspaceServiceGetArchitectureVersionProcedure is the fully-qualified name of the
	// WorkspaceService's GetArchitectureVersion RPC.
	WorkspaceServiceGetArchitectureVersionProcedure = "/loadline.v1.WorkspaceService/GetArchitectureVersion"
	// WorkspaceServiceListArchitectureVersionsProcedure is the fully-qualified name of the
	// WorkspaceService's ListArchitectureVersions RPC.
	WorkspaceServiceListArchitectureVersionsProcedure = "/loadline.v1.WorkspaceService/ListArchitectureVersions"
	// WorkspaceServiceCreateWorkloadProcedure is the fully-qualified name of the WorkspaceService's
	// CreateWorkload RPC.
	WorkspaceServiceCreateWorkloadProcedure = "/loadline.v1.WorkspaceService/CreateWorkload"
	// WorkspaceServiceGetWorkloadProcedure is the fully-qualified name of the WorkspaceService's
	// GetWorkload RPC.
	WorkspaceServiceGetWorkloadProcedure = "/loadline.v1.WorkspaceService/GetWorkload"
	// WorkspaceServiceListWorkloadsProcedure is the fully-qualified name of the WorkspaceService's
	// ListWorkloads RPC.
	WorkspaceServiceListWorkloadsProcedure = "/loadline.v1.WorkspaceService/ListWorkloads"
	// WorkspaceServiceUpdateWorkloadProcedure is the fully-qualified name of the WorkspaceService's
	// UpdateWorkload RPC.
	WorkspaceServiceUpdateWorkloadProcedure = "/loadline.v1.WorkspaceService/UpdateWorkload"
	// WorkspaceServiceDeleteWorkloadProcedure is the fully-qualified name of the WorkspaceService's
	// DeleteWorkload RPC.
	WorkspaceServiceDeleteWorkloadProcedure = "/loadline.v1.WorkspaceService/DeleteWorkload"
	// WorkspaceServiceExecuteSimulationProcedure is the fully-qualified name of the WorkspaceService's
	// ExecuteSimulation RPC.
	WorkspaceServiceExecuteSimulationProcedure = "/loadline.v1.WorkspaceService/ExecuteSimulation"
	// WorkspaceServiceGetSimulationRunProcedure is the fully-qualified name of the WorkspaceService's
	// GetSimulationRun RPC.
	WorkspaceServiceGetSimulationRunProcedure = "/loadline.v1.WorkspaceService/GetSimulationRun"
	// WorkspaceServiceListSimulationRunsProcedure is the fully-qualified name of the WorkspaceService's
	// ListSimulationRuns RPC.
	WorkspaceServiceListSimulationRunsProcedure = "/loadline.v1.WorkspaceService/ListSimulationRuns"
)

// WorkspaceServiceClient is a client for the loadline.v1.WorkspaceService service.
type WorkspaceServiceClient interface {
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error)
	// --- Architectures ------------------------------------------------------
	// Create an architecture and its first version in one transaction.
	CreateArchitecture(context.Context, *connect.Request[v1.CreateArchitectureRequest]) (*connect.Response[v1.CreateArchitectureResponse], error)
	GetArchitecture(context.Context, *connect.Request[v1.GetArchitectureRequest]) (*connect.Response[v1.GetArchitectureResponse], error)
	ListArchitectures(context.Context, *connect.Request[v1.ListArchitecturesRequest]) (*connect.Response[v1.ListArchitecturesResponse], error)
	UpdateArchitecture(context.Context, *connect.Request[v1.UpdateArchitectureRequest]) (*connect.Response[v1.UpdateArchitectureResponse], error)
	DeleteArchitecture(context.Context, *connect.Request[v1.DeleteArchitectureRequest]) (*connect.Response[v1.DeleteArchitectureResponse], error)
	// --- Architecture versions (immutable) ----------------------------------
	CreateArchitectureVersion(context.Context, *connect.Request[v1.CreateArchitectureVersionRequest]) (*connect.Response[v1.CreateArchitectureVersionResponse], error)
	GetArchitectureVersion(context.Context, *connect.Request[v1.GetArchitectureVersionRequest]) (*connect.Response[v1.GetArchitectureVersionResponse], error)
	ListArchitectureVersions(context.Context, *connect.Request[v1.ListArchitectureVersionsRequest]) (*connect.Response[v1.ListArchitectureVersionsResponse], error)
	// --- Workloads ----------------------------------------------------------
	CreateWorkload(context.Context, *connect.Request[v1.CreateWorkloadRequest]) (*connect.Response[v1.CreateWorkloadResponse], error)
	GetWorkload(context.Context, *connect.Request[v1.GetWorkloadRequest]) (*connect.Response[v1.GetWorkloadResponse], error)
	ListWorkloads(context.Context, *connect.Request[v1.ListWorkloadsRequest]) (*connect.Response[v1.ListWorkloadsResponse], error)
	UpdateWorkload(context.Context, *connect.Request[v1.UpdateWorkloadRequest]) (*connect.Response[v1.UpdateWorkloadResponse], error)
	DeleteWorkload(context.Context, *connect.Request[v1.DeleteWorkloadRequest]) (*connect.Response[v1.DeleteWorkloadResponse], error)
	// --- Simulation runs ----------------------------------------------------
	// Execute a stored version + workload on the simulation engine and persist
	// the run with its result summary in one transaction.
	ExecuteSimulation(context.Context, *connect.Request[v1.ExecuteSimulationRequest]) (*connect.Response[v1.ExecuteSimulationResponse], error)
	GetSimulationRun(context.Context, *connect.Request[v1.GetSimulationRunRequest]) (*connect.Response[v1.GetSimulationRunResponse], error)
	ListSimulationRuns(context.Context, *connect.Request[v1.ListSimulationRunsRequest]) (*connect.Response[v1.ListSimulationRunsResponse], error)
}

// NewWorkspaceServiceClient constructs a client for the loadline.v1.WorkspaceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkspaceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkspaceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workspaceServiceMethods := v1.File_loadline_v1_workspace_proto.Services().ByName("WorkspaceService").Methods()
	return &workspaceServiceClient{
		createProject: connect.NewClient[v1.CreateProjectRequest, v1.CreateProjectResponse](
			httpClient,
			baseURL+WorkspaceServiceCreateProjectProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		getProject: connect.NewClient[v1.GetProjectRequest, v1.GetProjectResponse](
			httpClient,
			baseURL+WorkspaceServiceGetProjectProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("GetProject")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+WorkspaceServiceListProjectsProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		updateProject: connect.NewClient[v1.UpdateProjectRequest, v1.UpdateProjectResponse](
			httpClient,
			baseURL+WorkspaceServiceUpdateProjectProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("UpdateProject")),
			connect.WithClientOptions(opts...),
		),
		deleteProject: connect.NewClient[v1.DeleteProjectRequest, v1.DeleteProjectResponse](
			httpClient,
			baseURL+WorkspaceServiceDeleteProjectProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("DeleteProject")),
			connect.WithClientOptions(opts...),
		),
		createArchitecture: connect.NewClient[v1.CreateArchitectureRequest, v1.CreateArchitectureResponse](
			httpClient,
			baseURL+WorkspaceServiceCreateArchitectureProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("CreateArchitecture")),
			connect.WithClientOptions(opts...),
		),
		getArchitecture: connect.NewClient[v1.GetArchitectureRequest, v1.GetArchitectureResponse](
			httpClient,
			baseURL+WorkspaceServiceGetArchitectureProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("GetArchitecture")),
			connect.WithClientOptions(opts...),
		),
		listArchitectures: connect.NewClient[v1.ListArchitecturesRequest, v1.ListArchitecturesResponse](
			httpClient,
			baseURL+WorkspaceServiceListArchitecturesProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("ListArchitectures")),
			connect.WithClientOptions(opts...),
		),
		updateArchitecture: connect.NewClient[v1.UpdateArchitectureRequest, v1.UpdateArchitectureResponse](
			httpClient,
			baseURL+WorkspaceServiceUpdateArchitectureProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("UpdateArchitecture")),
			connect.WithClientOptions(opts...),
		),
		deleteArchitecture: connect.NewClient[v1.DeleteArchitectureRequest, v1.DeleteArchitectureResponse](
			httpClient,
			baseURL+WorkspaceServiceDeleteArchitectureProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("DeleteArchitecture")),
			connect.WithClientOptions(opts...),
		),
		createArchitectureVersion: connect.NewClient[v1.CreateArchitectureVersionRequest, v1.CreateArchitectureVersionResponse](
			httpClient,
			baseURL+WorkspaceServiceCreateArchitectureVersionProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("CreateArchitectureVersion")),
			connect.WithClientOptions(opts...),
		),
		getArchitectureVersion: connect.NewClient[v1.GetArchitectureVersionRequest, v1.GetArchitectureVersionResponse](
			httpClient,
			baseURL+WorkspaceServiceGetArchitectureVersionProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("GetArchitectureVersion")),
			connect.WithClientOptions(opts...),
		),
		listArchitectureVersions: connect.NewClient[v1.ListArchitectureVersionsRequest, v1.ListArchitectureVersionsResponse](
			httpClient,
			baseURL+WorkspaceServiceListArchitectureVersionsProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("ListArchitectureVersions")),
			connect.WithClientOptions(opts...),
		),
		createWorkload: connect.NewClient[v1.CreateWorkloadRequest, v1.CreateWorkloadResponse](
			httpClient,
			baseURL+WorkspaceServiceCreateWorkloadProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("CreateWorkload")),
			connect.WithClientOptions(opts...),
		),
		getWorkload: connect.NewClient[v1.GetWorkloadRequest, v1.GetWorkloadResponse](
			httpClient,
			baseURL+WorkspaceServiceGetWorkloadProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("GetWorkload")),
			connect.WithClientOptions(opts...),
		),
		listWorkloads: connect.NewClient[v1.ListWorkloadsRequest, v1.ListWorkloadsResponse](
			httpClient,
			baseURL+WorkspaceServiceListWorkloadsProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("ListWorkloads")),
			connect.WithClientOptions(opts...),
		),
		updateWorkload: connect.NewClient[v1.UpdateWorkloadRequest, v1.UpdateWorkloadResponse](
			httpClient,
			baseURL+WorkspaceServiceUpdateWorkloadProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("UpdateWorkload")),
			connect.WithClientOptions(opts...),
		),
		deleteWorkload: connect.NewClient[v1.DeleteWorkloadRequest, v1.DeleteWorkloadResponse](
			httpClient,
			baseURL+WorkspaceServiceDeleteWorkloadProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("DeleteWorkload")),
			connect.WithClientOptions(opts...),
		),
		executeSimulation: connect.NewClient[v1.ExecuteSimulationRequest, v1.ExecuteSimulationResponse](
			httpClient,
			baseURL+WorkspaceServiceExecuteSimulationProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("ExecuteSimulation")),
			connect.WithClientOptions(opts...),
		),
		getSimulationRun: connect.NewClient[v1.GetSimulationRunRequest, v1.GetSimulationRunResponse](
			httpClient,
			baseURL+WorkspaceServiceGetSimulationRunProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("GetSimulationRun")),
			connect.WithClientOptions(opts...),
		),
		listSimulationRuns: connect.NewClient[v1.ListSimulationRunsRequest, v1.ListSimulationRunsResponse](
			httpClient,
			baseURL+WorkspaceServiceListSimulationRunsProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("ListSimulationRuns")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workspaceServiceClient implements WorkspaceServiceClient.
type workspaceServiceClient struct {
	createProject             *connect.Client[v1.CreateProjectRequest, v1.CreateProjectResponse]
	getProject                *connect.Client[v1.GetProjectRequest, v1.GetProjectResponse]
	listProjects              *connect.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
	updateProject             *connect.Client[v1.UpdateProjectRequest, v1.UpdateProjectResponse]
	deleteProject             *connect.Client[v1.DeleteProjectRequest, v1.DeleteProjectResponse]
	createArchitecture        *connect.Client[v1.CreateArchitectureRequest, v1.CreateArchitectureResponse]
	getArchitecture           *connect.Client[v1.GetArchitectureRequest, v1.GetArchitectureResponse]
	listArchitectures         *connect.Client[v1.ListArchitecturesRequest, v1.ListArchitecturesResponse]
	updateArchitecture        *connect.Client[v1.UpdateArchitectureRequest, v1.UpdateArchitectureResponse]
	deleteArchitecture        *connect.Client[v1.DeleteArchitectureRequest, v1.DeleteArchitectureResponse]
	createArchitectureVersion *connect.Client[v1.CreateArchitectureVersionRequest, v1.CreateArchitectureVersionResponse]
	getArchitectureVersion    *connect.Client[v1.GetArchitectureVersionRequest, v1.GetArchitectureVersionResponse]
	listArchitectureVersions  *connect.Client[v1.ListArchitectureVersionsRequest, v1.ListArchitectureVersionsResponse]
	createWorkload            *connect.Client[v1.CreateWorkloadRequest, v1.CreateWorkloadResponse]
	getWorkload               *connect.Client[v1.GetWorkloadRequest, v1.GetWorkloadResponse]
	listWorkloads             *connect.Client[v1.ListWorkloadsRequest, v1.ListWorkloadsResponse]
	updateWorkload            *connect.Client[v1.UpdateWorkloadRequest, v1.UpdateWorkloadResponse]
	deleteWorkload            *connect.Client[v1.DeleteWorkloadRequest, v1.DeleteWorkloadResponse]
	executeSimulation         *connect.Client[v1.ExecuteSimulationRequest, v1.ExecuteSimulationResponse]
	getSimulationRun          *connect.Client[v1.GetSimulationRunRequest, v1.GetSimulationRunResponse]
	listSimulationRuns        *connect.Client[v1.ListSimulationRunsRequest, v1.ListSimulationRunsResponse]
}

// CreateProject calls loadline.v1.WorkspaceService.CreateProject.
func (c *workspaceServiceClient) CreateProject(ctx context.Context, req *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// GetProject calls loadline.v1.WorkspaceService.GetProject.
func (c *workspaceServiceClient) GetProject(ctx context.Context, req *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error) {
	return c.getProject.CallUnary(ctx, req)
}

// ListProjects calls loadline.v1.WorkspaceService.ListProjects.
func (c *workspaceServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// UpdateProject calls loadline.v1.WorkspaceService.UpdateProject.
func (c *workspaceServiceClient) UpdateProject(ctx context.Context, req *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return c.updateProject.CallUnary(ctx, req)
}

// DeleteProject calls loadline.v1.WorkspaceService.DeleteProject.
func (c *workspaceServiceClient) DeleteProject(ctx context.Context, req *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error) {
	return c.deleteProject.CallUnary(ctx, req)
}

// CreateArchitecture calls loadline.v1.WorkspaceService.CreateArchitecture.
func (c *workspaceServiceClient) CreateArchitecture(ctx context.Context, req *connect.Request[v1.CreateArchitectureRequest]) (*connect.Response[v1.CreateArchitectureResponse], error) {
	return c.createArchitecture.CallUnary(ctx, req)
}

// GetArchitecture calls loadline.v1.WorkspaceService.GetArchitecture.
func (c *workspaceServiceClient) GetArchitecture(ctx context.Context, req *connect.Request[v1.GetArchitectureRequest]) (*connect.Response[v1.GetArchitectureResponse], error) {
	return c.getArchitecture.CallUnary(ctx, req)
}

// ListArchitectures calls loadline.v1.WorkspaceService.ListArchitectures.
func (c *workspaceServiceClient) ListArchitectures(ctx context.Context, req *connect.Request[v1.ListArchitecturesRequest]) (*connect.Response[v1.ListArchitecturesResponse], error) {
	return c.listArchitectures.CallUnary(ctx, req)
}

// UpdateArchitecture calls loadline.v1.WorkspaceService.UpdateArchitecture.
func (c *workspaceServiceClient) UpdateArchitecture(ctx context.Context, req *connect.Request[v1.UpdateArchitectureRequest]) (*connect.Response[v1.UpdateArchitectureResponse], error) {
	return c.updateArchitecture.CallUnary(ctx, req)
}

// DeleteArchitecture calls loadline.v1.WorkspaceService.DeleteArchitecture.
func (c *workspaceServiceClient) DeleteArchitecture(ctx context.Context, req *connect.Request[v1.DeleteArchitectureRequest]) (*connect.Response[v1.DeleteArchitectureResponse], error) {
	return c.deleteArchitecture.CallUnary(ctx, req)
}

// CreateArchitectureVersion calls loadline.v1.WorkspaceService.CreateArchitectureVersion.
func (c *workspaceServiceClient) CreateArchitectureVersion(ctx context.Context, req *connect.Request[v1.CreateArchitectureVersionRequest]) (*connect.Response[v1.CreateArchitectureVersionResponse], error) {
	return c.createArchitectureVersion.CallUnary(ctx, req)
}

// GetArchitectureVersion calls loadline.v1.WorkspaceService.GetArchitectureVersion.
func (c *workspaceServiceClient) GetArchitectureVersion(ctx context.Context, req *connect.Request[v1.GetArchitectureVersionRequest]) (*connect.Response[v1.GetArchitectureVersionResponse], error) {
	return c.getArchitectureVersion.CallUnary(ctx, req)
}

// ListArchitectureVersions calls loadline.v1.WorkspaceService.ListArchitectureVersions.
func (c *workspaceServiceClient) ListArchitectureVersions(ctx context.Context, req *connect.Request[v1.ListArchitectureVersionsRequest]) (*connect.Response[v1.ListArchitectureVersionsResponse], error) {
	return c.listArchitectureVersions.CallUnary(ctx, req)
}

// CreateWorkload calls loadline.v1.WorkspaceService.CreateWorkload.
func (c *workspaceServiceClient) CreateWorkload(ctx context.Context, req *connect.Request[v1.CreateWorkloadRequest]) (*connect.Response[v1.CreateWorkloadResponse], error) {
	return c.createWorkload.CallUnary(ctx, req)
}

// GetWorkload calls loadline.v1.WorkspaceService.GetWorkload.
func (c *workspaceServiceClient) GetWorkload(ctx context.Context, req *connect.Request[v1.GetWorkloadRequest]) (*connect.Response[v1.GetWorkloadResponse], error) {
	return c.getWorkload.CallUnary(ctx, req)
}

// ListWorkloads calls loadline.v1.WorkspaceService.ListWorkloads.
func (c *workspaceServiceClient) ListWorkloads(ctx context.Context, req *connect.Request[v1.ListWorkloadsRequest]) (*connect.Response[v1.ListWorkloadsResponse], error) {
	return c.listWorkloads.CallUnary(ctx, req)
}

// UpdateWorkload calls loadline.v1.WorkspaceService.UpdateWorkload.
func (c *workspaceServiceClient) UpdateWorkload(ctx context.Context, req *connect.Request[v1.UpdateWorkloadRequest]) (*connect.Response[v1.UpdateWorkloadResponse], error) {
	return c.updateWorkload.CallUnary(ctx, req)
}

// DeleteWorkload calls loadline.v1.WorkspaceService.DeleteWorkload.
func (c *workspaceServiceClient) DeleteWorkload(ctx context.Context, req *connect.Request[v1.DeleteWorkloadRequest]) (*connect.Response[v1.DeleteWorkloadResponse], error) {
	return c.deleteWorkload.CallUnary(ctx, req)
}

// ExecuteSimulation calls loadline.v1.WorkspaceService.ExecuteSimulation.
func (c *workspaceServiceClient) ExecuteSimulation(ctx context.Context, req *connect.Request[v1.ExecuteSimulationRequest]) (*connect.Response[v1.ExecuteSimulationResponse], error) {
	return c.executeSimulation.CallUnary(ctx, req)
}

// GetSimulationRun calls loadline.v1.WorkspaceService.GetSimulationRun.
func (c *workspaceServiceClient) GetSimulationRun(ctx context.Context, req *connect.Request[v1.GetSimulationRunRequest]) (*connect.Response[v1.GetSimulationRunResponse], error) {
	return c.getSimulationRun.CallUnary(ctx, req)
}

// ListSimulationRuns calls loadline.v1.WorkspaceService.ListSimulationRuns.
func (c *workspaceServiceClient) ListSimulationRuns(ctx context.Context, req *connect.Request[v1.ListSimulationRunsRequest]) (*connect.Response[v1.ListSimulationRunsResponse], error) {
	return c.listSimulationRuns.CallUnary(ctx, req)
}

// WorkspaceServiceHandler is an implementation of the loadline.v1.WorkspaceService service.
type WorkspaceServiceHandler interface {
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error)
	// --- Architectures ------------------------------------------------------
	// Create an architecture and its first version in one transaction.
	CreateArchitecture(context.Context, *connect.Request[v1.CreateArchitectureRequest]) (*connect.Response[v1.CreateArchitectureResponse], error)
	GetArchitecture(context.Context, *connect.Request[v1.GetArchitectureRequest]) (*connect.Response[v1.GetArchitectureResponse], error)
	ListArchitectures(context.Context, *connect.Request[v1.ListArchitecturesRequest]) (*connect.Response[v1.ListArchitecturesResponse], error)
	UpdateArchitecture(context.Context, *connect.Request[v1.UpdateArchitectureRequest]) (*connect.Response[v1.UpdateArchitectureResponse], error)
	DeleteArchitecture(context.Context, *connect.Request[v1.DeleteArchitectureRequest]) (*connect.Response[v1.DeleteArchitectureResponse], error)
	// --- Architecture versions (immutable) ----------------------------------
	CreateArchitectureVersion(context.Context, *connect.Request[v1.CreateArchitectureVersionRequest]) (*connect.Response[v1.CreateArchitectureVersionResponse], error)
	GetArchitectureVersion(context.Context, *connect.Request[v1.GetArchitectureVersionRequest]) (*connect.Response[v1.GetArchitectureVersionResponse], error)
	ListArchitectureVersions(context.Context, *connect.Request[v1.ListArchitectureVersionsRequest]) (*connect.Response[v1.ListArchitectureVersionsResponse], error)
	// --- Workloads ----------------------------------------------------------
	CreateWorkload(context.Context, *connect.Request[v1.CreateWorkloadRequest]) (*connect.Response[v1.CreateWorkloadResponse], error)
	GetWorkload(context.Context, *connect.Request[v1.GetWorkloadRequest]) (*connect.Response[v1.GetWorkloadResponse], error)
	ListWorkloads(context.Context, *connect.Request[v1.ListWorkloadsRequest]) (*connect.Response[v1.ListWorkloadsResponse], error)
	UpdateWorkload(context.Context, *connect.Request[v1.UpdateWorkloadRequest]) (*connect.Response[v1.UpdateWorkloadResponse], error)
	DeleteWorkload(context.Context, *connect.Request[v1.DeleteWorkloadRequest]) (*connect.Response[v1.DeleteWorkloadResponse], error)
	// --- Simulation runs ----------------------------------------------------
	// Execute a stored version + workload on the simulation engine and persist
	// the run with its result summary in one transaction.
	ExecuteSimulation(context.Context, *connect.Request[v1.ExecuteSimulationRequest]) (*connect.Response[v1.ExecuteSimulationResponse], error)
	GetSimulationRun(context.Context, *connect.Request[v1.GetSimulationRunRequest]) (*connect.Response[v1.GetSimulationRunResponse], error)
	ListSimulationRuns(context.Context, *connect.Request[v1.ListSimulationRunsRequest]) (*connect.Response[v1.ListSimulationRunsResponse], error)
}

// NewWorkspaceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkspaceServiceHandler(svc WorkspaceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workspaceServiceMethods := v1.File_loadline_v1_workspace_proto.Services().ByName("WorkspaceService").Methods()
	workspaceServiceCreateProjectHandler := connect.NewUnaryHandler(
		WorkspaceServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(workspaceServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceGetProjectHandler := connect.NewUnaryHandler(
		WorkspaceServiceGetProjectProcedure,
		svc.GetProject,
		connect.WithSchema(workspaceServiceMethods.ByName("GetProject")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceListProjectsHandler := connect.NewUnaryHandler(
		WorkspaceServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(workspaceServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceUpdateProjectHandler := connect.NewUnaryHandler(
		WorkspaceServiceUpdateProjectProcedure,
		svc.UpdateProject,
		connect.WithSchema(workspaceServiceMethods.ByName("UpdateProject")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceDeleteProjectHandler := connect.NewUnaryHandler(
		WorkspaceServiceDeleteProjectProcedure,
		svc.DeleteProject,
		connect.WithSchema(workspaceServiceMethods.ByName("DeleteProject")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceCreateArchitectureHandler := connect.NewUnaryHandler(
		WorkspaceServiceCreateArchitectureProcedure,
		svc.CreateArchitecture,
		connect.WithSchema(workspaceServiceMethods.ByName("CreateArchitecture")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceGetArchitectureHandler := connect.NewUnaryHandler(
		WorkspaceServiceGetArchitectureProcedure,
		svc.GetArchitecture,
		connect.WithSchema(workspaceServiceMethods.ByName("GetArchitecture")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceListArchitecturesHandler := connect.NewUnaryHandler(
		WorkspaceServiceListArchitecturesProcedure,
		svc.ListArchitectures,
		connect.WithSchema(workspaceServiceMethods.ByName("ListArchitectures")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceUpdateArchitectureHandler := connect.NewUnaryHandler(
		WorkspaceServiceUpdateArchitectureProcedure,
		svc.UpdateArchitecture,
		connect.WithSchema(workspaceServiceMethods.ByName("UpdateArchitecture")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceDeleteArchitectureHandler := connect.NewUnaryHandler(
		WorkspaceServiceDeleteArchitectureProcedure,
		svc.DeleteArchitecture,
		connect.WithSchema(workspaceServiceMethods.ByName("DeleteArchitecture")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceCreateArchitectureVersionHandler := connect.NewUnaryHandler(
		WorkspaceServiceCreateArchitectureVersionProcedure,
		svc.CreateArchitectureVersion,
		connect.WithSchema(workspaceServiceMethods.ByName("CreateArchitectureVersion")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceGetArchitectureVersionHandler := connect.NewUnaryHandler(
		WorkspaceServiceGetArchitectureVersionProcedure,
		svc.GetArchitectureVersion,
		connect.WithSchema(workspaceServiceMethods.ByName("GetArchitectureVersion")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceListArchitectureVersionsHandler := connect.NewUnaryHandler(
		WorkspaceServiceListArchitectureVersionsProcedure,
		svc.ListArchitectureVersions,
		connect.WithSchema(workspaceServiceMethods.ByName("ListArchitectureVersions")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceCreateWorkloadHandler := connect.NewUnaryHandler(
		WorkspaceServiceCreateWorkloadProcedure,
		svc.CreateWorkload,
		connect.WithSchema(workspaceServiceMethods.ByName("CreateWorkload")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceGetWorkloadHandler := connect.NewUnaryHandler(
		WorkspaceServiceGetWorkloadProcedure,
		svc.GetWorkload,
		connect.WithSchema(workspaceServiceMethods.ByName("GetWorkload")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceListWorkloadsHandler := connect.NewUnaryHandler(
		WorkspaceServiceListWorkloadsProcedure,
		svc.ListWorkloads,
		connect.WithSchema(workspaceServiceMethods.ByName("ListWorkloads")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceUpdateWorkloadHandler := connect.NewUnaryHandler(
		WorkspaceServiceUpdateWorkloadProcedure,
		svc.UpdateWorkload,
		connect.WithSchema(workspaceServiceMethods.ByName("UpdateWorkload")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceDeleteWorkloadHandler := connect.NewUnaryHandler(
		WorkspaceServiceDeleteWorkloadProcedure,
		svc.DeleteWorkload,
		connect.WithSchema(workspaceServiceMethods.ByName("DeleteWorkload")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceExecuteSimulationHandler := connect.NewUnaryHandler(
		WorkspaceServiceExecuteSimulationProcedure,
		svc.ExecuteSimulation,
		connect.WithSchema(workspaceServiceMethods.ByName("ExecuteSimulation")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceGetSimulationRunHandler := connect.NewUnaryHandler(
		WorkspaceServiceGetSimulationRunProcedure,
		svc.GetSimulationRun,
		connect.WithSchema(workspaceServiceMethods.ByName("GetSimulationRun")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceListSimulationRunsHandler := connect.NewUnaryHandler(
		WorkspaceServiceListSimulationRunsProcedure,
		svc.ListSimulationRuns,
		connect.WithSchema(workspaceServiceMethods.ByName("ListSimulationRuns")),
		connect.WithHandlerOptions(opts...),
	)
	return "/loadline.v1.WorkspaceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkspaceServiceCreateProjectProcedure:
			workspaceServiceCreateProjectHandler.ServeHTTP(w, r)
		case WorkspaceServiceGetProjectProcedure:
			workspaceServiceGetProjectHandler.ServeHTTP(w, r)
		case WorkspaceServiceListProjectsProcedure:
			workspaceServiceListProjectsHandler.ServeHTTP(w, r)
		case WorkspaceServiceUpdateProjectProcedure:
			workspaceServiceUpdateProjectHandler.ServeHTTP(w, r)
		case WorkspaceServiceDeleteProjectProcedure:
			workspaceServiceDeleteProjectHandler.ServeHTTP(w, r)
		case WorkspaceServiceCreateArchitectureProcedure:
			workspaceServiceCreateArchitectureHandler.ServeHTTP(w, r)
		case WorkspaceServiceGetArchitectureProcedure:
			workspaceServiceGetArchitectureHandler.ServeHTTP(w, r)
		case WorkspaceServiceListArchitecturesProcedure:
			workspaceServiceListArchitecturesHandler.ServeHTTP(w, r)
		case WorkspaceServiceUpdateArchitectureProcedure:
			workspaceServiceUpdateArchitectureHandler.ServeHTTP(w, r)
		case WorkspaceServiceDeleteArchitectureProcedure:
			workspaceServiceDeleteArchitectureHandler.ServeHTTP(w, r)
		case WorkspaceServiceCreateArchitectureVersionProcedure:
			workspaceServiceCreateArchitectureVersionHandler.ServeHTTP(w, r)
		case WorkspaceServiceGetArchitectureVersionProcedure:
			workspaceServiceGetArchitectureVersionHandler.ServeHTTP(w, r)
		case WorkspaceServiceListArchitectureVersionsProcedure:
			workspaceServiceListArchitectureVersionsHandler.ServeHTTP(w, r)
		case WorkspaceServiceCreateWorkloadProcedure:
			workspaceServiceCreateWorkloadHandler.ServeHTTP(w, r)
		case WorkspaceServiceGetWorkloadProcedure:
			workspaceServiceGetWorkloadHandler.ServeHTTP(w, r)
		case WorkspaceServiceListWorkloadsProcedure:
			workspaceServiceListWorkloadsHandler.ServeHTTP(w, r)
		case WorkspaceServiceUpdateWorkloadProcedure:
			workspaceServiceUpdateWorkloadHandler.ServeHTTP(w, r)
		case WorkspaceServiceDeleteWorkloadProcedure:
			workspaceServiceDeleteWorkloadHandler.ServeHTTP(w, r)
		case WorkspaceServiceExecuteSimulationProcedure:
			workspaceServiceExecuteSimulationHandler.ServeHTTP(w, r)
		case WorkspaceServiceGetSimulationRunProcedure:
			workspaceServiceGetSimulationRunHandler.ServeHTTP(w, r)
		case WorkspaceServiceListSimulationRunsProcedure:
			workspaceServiceListSimulationRunsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkspaceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkspaceServiceHandler struct{}

func (UnimplementedWorkspaceServiceHandler) CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.CreateProject is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.GetProject is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.ListProjects is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.UpdateProject is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) DeleteProject(context.Context, *connect.Request[v1.DeleteProjectRequest]) (*connect.Response[v1.DeleteProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.DeleteProject is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) CreateArchitecture(context.Context, *connect.Request[v1.CreateArchitectureRequest]) (*connect.Response[v1.CreateArchitectureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.CreateArchitecture is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) GetArchitecture(context.Context, *connect.Request[v1.GetArchitectureRequest]) (*connect.Response[v1.GetArchitectureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.GetArchitecture is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) ListArchitectures(context.Context, *connect.Request[v1.ListArchitecturesRequest]) (*connect.Response[v1.ListArchitecturesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.ListArchitectures is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) UpdateArchitecture(context.Context, *connect.Request[v1.UpdateArchitectureRequest]) (*connect.Response[v1.UpdateArchitectureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.UpdateArchitecture is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) DeleteArchitecture(context.Context, *connect.Request[v1.DeleteArchitectureRequest]) (*connect.Response[v1.DeleteArchitectureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.DeleteArchitecture is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) CreateArchitectureVersion(context.Context, *connect.Request[v1.CreateArchitectureVersionRequest]) (*connect.Response[v1.CreateArchitectureVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.CreateArchitectureVersion is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) GetArchitectureVersion(context.Context, *connect.Request[v1.GetArchitectureVersionRequest]) (*connect.Response[v1.GetArchitectureVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.GetArchitectureVersion is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) ListArchitectureVersions(context.Context, *connect.Request[v1.ListArchitectureVersionsRequest]) (*connect.Response[v1.ListArchitectureVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.ListArchitectureVersions is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) CreateWorkload(context.Context, *connect.Request[v1.CreateWorkloadRequest]) (*connect.Response[v1.CreateWorkloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.CreateWorkload is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) GetWorkload(context.Context, *connect.Request[v1.GetWorkloadRequest]) (*connect.Response[v1.GetWorkloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.GetWorkload is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) ListWorkloads(context.Context, *connect.Request[v1.ListWorkloadsRequest]) (*connect.Response[v1.ListWorkloadsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.ListWorkloads is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) UpdateWorkload(context.Context, *connect.Request[v1.UpdateWorkloadRequest]) (*connect.Response[v1.UpdateWorkloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.UpdateWorkload is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) DeleteWorkload(context.Context, *connect.Request[v1.DeleteWorkloadRequest]) (*connect.Response[v1.DeleteWorkloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.DeleteWorkload is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) ExecuteSimulation(context.Context, *connect.Request[v1.ExecuteSimulationRequest]) (*connect.Response[v1.ExecuteSimulationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.ExecuteSimulation is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) GetSimulationRun(context.Context, *connect.Request[v1.GetSimulationRunRequest]) (*connect.Response[v1.GetSimulationRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.GetSimulationRun is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) ListSimulationRuns(context.Context, *connect.Request[v1.ListSimulationRunsRequest]) (*connect.Response[v1.ListSimulationRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loadline.v1.WorkspaceService.ListSimulationRuns is not implemented"))
}
