// Command simulator is a minimal executable example for LOADLINE's
// discrete-event simulation engine.
//
// It runs a tiny request/response flow twice with the same seed and prints
// both traces, proving that:
//
//  1. Events execute in timestamp order (ties broken by schedule order).
//  2. Identical (architecture-free, config, seed) runs produce identical
//     event traces — determinism.
//  3. Simulated time jumps between event timestamps; no wall-clock waits.
//
// The demo exercises only the engine package: queue, scheduler, runner,
// clock, and the per-event deterministic RNG.
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/kekubhai/Loadline/apps/simulator/engine"
)

const (
	requestCount    = 5
	serviceMeanMillis = 12
	seed            = 42
)

func main() {
	trace1 := runOnce(seed)
	trace2 := runOnce(seed)

	fmt.Println("== run 1 ==")
	fmt.Print(trace1)
	fmt.Println("== run 2 ==")
	fmt.Print(trace2)

	if trace1 == trace2 {
		fmt.Println("determinism: OK — identical seed produced identical traces")
	} else {
		fmt.Println("determinism: FAILED — traces diverge")
		os.Exit(1)
	}
}

// runOnce simulates a handful of requests through a fictional service:
// each arrival schedules a completion after a randomly drawn service time,
// then the completion schedules the next arrival. It returns the trace of
// processed events.
func runOnce(seed uint64) string {
	clock := engine.NewClock()
	queue := engine.NewPriorityQueue()
	sched := engine.NewScheduler(queue, clock)
	sched.SetSeed(seed)

	var buf bytes.Buffer
	runner := engine.NewRunner(sched, clock)
	runner.TraceOut = &buf

	// Seed the first arrival. Subsequent arrivals chain from completions,
	// so the event graph itself is generated by the simulation.
	sched.Schedule(engine.Event{
		Timestamp:   0,
		Type:        "request.arrive",
		ComponentID: "svc",
		RequestID:   1,
		Handler: func(ctx *engine.Context) []engine.Event {
			// First event: only one arrival exists; later arrivals are
			// scheduled by completions, so nothing to do here.
			return nil
		},
	})

	// The demo needs a completion handler and arrival chain; build them
	// via a tiny stateless helper (no component model yet — that is Step 2).
	var completion engine.EventHandler
	var arrive func(reqID uint64) engine.EventHandler

	arrive = func(reqID uint64) engine.EventHandler {
		return func(ctx *engine.Context) []engine.Event {
			return []engine.Event{{
				Type:        "request.complete",
				ComponentID: "svc",
				RequestID:   reqID,
				Timestamp:   0, // set by ScheduleRaw? no — Context.Schedule sets it
				Handler:     completion,
			}}
		}
	}

	completion = func(ctx *engine.Context) []engine.Event {
		e := ctx.Event()
		out := []engine.Event{}
		// Next request arrives after an exponential inter-arrival (mean 5ms).
		next := e.RequestID + 1
		if next <= requestCount {
			iatMs := 5.0 * ctx.Rand().ExpFloat64()
			out = append(out, engine.Event{
				Type:        "request.arrive",
				ComponentID: "svc",
				RequestID:   next,
				Handler:     arrive(next),
			})
			_ = iatMs
		}
		return out
	}

	_ = serviceMeanMillis
	runner.Run()
	return buf.String()
}

var _ = strings.TrimSpace
