// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loadline/v1/arena.proto

package loadlinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChallengeConstraints are the targets the score is measured against. A zero
// field is "not assessed" for that dimension.
type ChallengeConstraints struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TargetThroughputRps float64                `protobuf:"fixed64,1,opt,name=target_throughput_rps,json=targetThroughputRps,proto3" json:"target_throughput_rps,omitempty"`
	TargetP95Ms         float64                `protobuf:"fixed64,2,opt,name=target_p95_ms,json=targetP95Ms,proto3" json:"target_p95_ms,omitempty"`
	TargetP99Ms         float64                `protobuf:"fixed64,3,opt,name=target_p99_ms,json=targetP99Ms,proto3" json:"target_p99_ms,omitempty"`
	TargetErrorRate     float64                `protobuf:"fixed64,4,opt,name=target_error_rate,json=targetErrorRate,proto3" json:"target_error_rate,omitempty"`
	MonthlyBudgetUsd    float64                `protobuf:"fixed64,5,opt,name=monthly_budget_usd,json=monthlyBudgetUsd,proto3" json:"monthly_budget_usd,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChallengeConstraints) Reset() {
	*x = ChallengeConstraints{}
	mi := &file_loadline_v1_arena_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeConstraints) ProtoMessage() {}

func (x *ChallengeConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeConstraints.ProtoReflect.Descriptor instead.
func (*ChallengeConstraints) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeConstraints) GetTargetThroughputRps() float64 {
	if x != nil {
		return x.TargetThroughputRps
	}
	return 0
}

func (x *ChallengeConstraints) GetTargetP95Ms() float64 {
	if x != nil {
		return x.TargetP95Ms
	}
	return 0
}

func (x *ChallengeConstraints) GetTargetP99Ms() float64 {
	if x != nil {
		return x.TargetP99Ms
	}
	return 0
}

func (x *ChallengeConstraints) GetTargetErrorRate() float64 {
	if x != nil {
		return x.TargetErrorRate
	}
	return 0
}

func (x *ChallengeConstraints) GetMonthlyBudgetUsd() float64 {
	if x != nil {
		return x.MonthlyBudgetUsd
	}
	return 0
}

// FailureScenario is one standardized injection. target_kind names a generic
// component kind ("cache"); the server resolves it to the submitted
// architecture's component of that kind. type is one of the engine's failure
// types: crash, increased_latency, increased_error_rate, network_failure.
type FailureScenario struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetKind     string                 `protobuf:"bytes,1,opt,name=target_kind,json=targetKind,proto3" json:"target_kind,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	StartMs        float64                `protobuf:"fixed64,3,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	DurationMs     float64                `protobuf:"fixed64,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	AddedLatencyMs float64                `protobuf:"fixed64,5,opt,name=added_latency_ms,json=addedLatencyMs,proto3" json:"added_latency_ms,omitempty"`
	ErrorRate      float64                `protobuf:"fixed64,6,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	PacketLossRate float64                `protobuf:"fixed64,7,opt,name=packet_loss_rate,json=packetLossRate,proto3" json:"packet_loss_rate,omitempty"`
	PassThrough    bool                   `protobuf:"varint,8,opt,name=pass_through,json=passThrough,proto3" json:"pass_through,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FailureScenario) Reset() {
	*x = FailureScenario{}
	mi := &file_loadline_v1_arena_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureScenario) ProtoMessage() {}

func (x *FailureScenario) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureScenario.ProtoReflect.Descriptor instead.
func (*FailureScenario) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{1}
}

func (x *FailureScenario) GetTargetKind() string {
	if x != nil {
		return x.TargetKind
	}
	return ""
}

func (x *FailureScenario) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FailureScenario) GetStartMs() float64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *FailureScenario) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *FailureScenario) GetAddedLatencyMs() float64 {
	if x != nil {
		return x.AddedLatencyMs
	}
	return 0
}

func (x *FailureScenario) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *FailureScenario) GetPacketLossRate() float64 {
	if x != nil {
		return x.PacketLossRate
	}
	return 0
}

func (x *FailureScenario) GetPassThrough() bool {
	if x != nil {
		return x.PassThrough
	}
	return false
}

// KindRequirement is a hard structural rule: at least min components of a
// generic component kind.
type KindRequirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Min           int32                  `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindRequirement) Reset() {
	*x = KindRequirement{}
	mi := &file_loadline_v1_arena_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindRequirement) ProtoMessage() {}

func (x *KindRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindRequirement.ProtoReflect.Descriptor instead.
func (*KindRequirement) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{2}
}

func (x *KindRequirement) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KindRequirement) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

// ScoringWeights are the relative weights of the five score dimensions.
type ScoringWeights struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Throughput      float64                `protobuf:"fixed64,1,opt,name=throughput,proto3" json:"throughput,omitempty"`
	Latency         float64                `protobuf:"fixed64,2,opt,name=latency,proto3" json:"latency,omitempty"`
	Reliability     float64                `protobuf:"fixed64,3,opt,name=reliability,proto3" json:"reliability,omitempty"`
	Cost            float64                `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`
	FailureRecovery float64                `protobuf:"fixed64,5,opt,name=failure_recovery,json=failureRecovery,proto3" json:"failure_recovery,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScoringWeights) Reset() {
	*x = ScoringWeights{}
	mi := &file_loadline_v1_arena_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoringWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoringWeights) ProtoMessage() {}

func (x *ScoringWeights) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoringWeights.ProtoReflect.Descriptor instead.
func (*ScoringWeights) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{3}
}

func (x *ScoringWeights) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *ScoringWeights) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *ScoringWeights) GetReliability() float64 {
	if x != nil {
		return x.Reliability
	}
	return 0
}

func (x *ScoringWeights) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ScoringWeights) GetFailureRecovery() float64 {
	if x != nil {
		return x.FailureRecovery
	}
	return 0
}

// FailureScenarioList is the stored form of a challenge's failures. A
// repeated field needs a message to be serialized on its own.
type FailureScenarioList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failures      []*FailureScenario     `protobuf:"bytes,1,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureScenarioList) Reset() {
	*x = FailureScenarioList{}
	mi := &file_loadline_v1_arena_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureScenarioList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureScenarioList) ProtoMessage() {}

func (x *FailureScenarioList) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureScenarioList.ProtoReflect.Descriptor instead.
func (*FailureScenarioList) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{4}
}

func (x *FailureScenarioList) GetFailures() []*FailureScenario {
	if x != nil {
		return x.Failures
	}
	return nil
}

// KindRequirementList is the stored form of a challenge's requirements.
type KindRequirementList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirements  []*KindRequirement     `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindRequirementList) Reset() {
	*x = KindRequirementList{}
	mi := &file_loadline_v1_arena_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindRequirementList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindRequirementList) ProtoMessage() {}

func (x *KindRequirementList) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindRequirementList.ProtoReflect.Descriptor instead.
func (*KindRequirementList) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{5}
}

func (x *KindRequirementList) GetRequirements() []*KindRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

// ChallengeSummary is the list/card view of a challenge.
type ChallengeSummary struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Slug        string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Version     int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// difficulty: beginner | intermediate | advanced | expert
	Difficulty string `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	// category: api | social | ecommerce | saas | realtime | distributed | cloud
	Category string `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	// status: draft | active | closed
	Status        string                `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Workload      *WorkloadSpec         `protobuf:"bytes,8,opt,name=workload,proto3" json:"workload,omitempty"`
	Constraints   *ChallengeConstraints `protobuf:"bytes,9,opt,name=constraints,proto3" json:"constraints,omitempty"`
	Failures      []*FailureScenario    `protobuf:"bytes,10,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeSummary) Reset() {
	*x = ChallengeSummary{}
	mi := &file_loadline_v1_arena_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeSummary) ProtoMessage() {}

func (x *ChallengeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeSummary.ProtoReflect.Descriptor instead.
func (*ChallengeSummary) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{6}
}

func (x *ChallengeSummary) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ChallengeSummary) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ChallengeSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChallengeSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChallengeSummary) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *ChallengeSummary) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ChallengeSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChallengeSummary) GetWorkload() *WorkloadSpec {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *ChallengeSummary) GetConstraints() *ChallengeConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *ChallengeSummary) GetFailures() []*FailureScenario {
	if x != nil {
		return x.Failures
	}
	return nil
}

// Challenge is the full definition, including exactly how submissions are
// evaluated. Nothing about the benchmark is hidden.
type Challenge struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Summary      *ChallengeSummary      `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Requirements []*KindRequirement     `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Scoring      *ScoringWeights        `protobuf:"bytes,3,opt,name=scoring,proto3" json:"scoring,omitempty"`
	// seed is the fixed benchmark seed; it is recorded on every submission.
	Seed          uint64  `protobuf:"varint,4,opt,name=seed,proto3" json:"seed,omitempty"`
	DurationMs    float64 `protobuf:"fixed64,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_loadline_v1_arena_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{7}
}

func (x *Challenge) GetSummary() *ChallengeSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Challenge) GetRequirements() []*KindRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Challenge) GetScoring() *ScoringWeights {
	if x != nil {
		return x.Scoring
	}
	return nil
}

func (x *Challenge) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *Challenge) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ListChallengesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChallengesRequest) Reset() {
	*x = ListChallengesRequest{}
	mi := &file_loadline_v1_arena_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChallengesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChallengesRequest) ProtoMessage() {}

func (x *ListChallengesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChallengesRequest.ProtoReflect.Descriptor instead.
func (*ListChallengesRequest) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{8}
}

type ListChallengesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// challenges are ordered by difficulty, then name.
	Challenges    []*ChallengeSummary `protobuf:"bytes,1,rep,name=challenges,proto3" json:"challenges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChallengesResponse) Reset() {
	*x = ListChallengesResponse{}
	mi := &file_loadline_v1_arena_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChallengesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChallengesResponse) ProtoMessage() {}

func (x *ListChallengesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChallengesResponse.ProtoReflect.Descriptor instead.
func (*ListChallengesResponse) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{9}
}

func (x *ListChallengesResponse) GetChallenges() []*ChallengeSummary {
	if x != nil {
		return x.Challenges
	}
	return nil
}

type GetChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeRequest) Reset() {
	*x = GetChallengeRequest{}
	mi := &file_loadline_v1_arena_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeRequest) ProtoMessage() {}

func (x *GetChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeRequest) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{10}
}

func (x *GetChallengeRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     *Challenge             `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeResponse) Reset() {
	*x = GetChallengeResponse{}
	mi := &file_loadline_v1_arena_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeResponse) ProtoMessage() {}

func (x *GetChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeResponse.ProtoReflect.Descriptor instead.
func (*GetChallengeResponse) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{11}
}

func (x *GetChallengeResponse) GetChallenge() *Challenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

// SubmitChallengeRequest is ALL the client may send. There is deliberately no
// seed, workload, score, rank, or metric field: the server owns the
// benchmark.
type SubmitChallengeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ChallengeSlug         string                 `protobuf:"bytes,1,opt,name=challenge_slug,json=challengeSlug,proto3" json:"challenge_slug,omitempty"`
	ArchitectureVersionId string                 `protobuf:"bytes,2,opt,name=architecture_version_id,json=architectureVersionId,proto3" json:"architecture_version_id,omitempty"`
	DisplayName           string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SubmitChallengeRequest) Reset() {
	*x = SubmitChallengeRequest{}
	mi := &file_loadline_v1_arena_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitChallengeRequest) ProtoMessage() {}

func (x *SubmitChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitChallengeRequest.ProtoReflect.Descriptor instead.
func (*SubmitChallengeRequest) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitChallengeRequest) GetChallengeSlug() string {
	if x != nil {
		return x.ChallengeSlug
	}
	return ""
}

func (x *SubmitChallengeRequest) GetArchitectureVersionId() string {
	if x != nil {
		return x.ArchitectureVersionId
	}
	return ""
}

func (x *SubmitChallengeRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// ScoreComponent is one dimension of the score with its derivation.
type ScoreComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Weighted      float64                `protobuf:"fixed64,4,opt,name=weighted,proto3" json:"weighted,omitempty"`
	Detail        string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	Evidence      []string               `protobuf:"bytes,6,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreComponent) Reset() {
	*x = ScoreComponent{}
	mi := &file_loadline_v1_arena_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreComponent) ProtoMessage() {}

func (x *ScoreComponent) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreComponent.ProtoReflect.Descriptor instead.
func (*ScoreComponent) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{13}
}

func (x *ScoreComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScoreComponent) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreComponent) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ScoreComponent) GetWeighted() float64 {
	if x != nil {
		return x.Weighted
	}
	return 0
}

func (x *ScoreComponent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ScoreComponent) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// ScoreBreakdown is the full, explainable score.
type ScoreBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	Components    []*ScoreComponent      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	Positives     []string               `protobuf:"bytes,3,rep,name=positives,proto3" json:"positives,omitempty"`
	Negatives     []string               `protobuf:"bytes,4,rep,name=negatives,proto3" json:"negatives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreBreakdown) Reset() {
	*x = ScoreBreakdown{}
	mi := &file_loadline_v1_arena_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreBreakdown) ProtoMessage() {}

func (x *ScoreBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreBreakdown.ProtoReflect.Descriptor instead.
func (*ScoreBreakdown) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{14}
}

func (x *ScoreBreakdown) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreBreakdown) GetComponents() []*ScoreComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ScoreBreakdown) GetPositives() []string {
	if x != nil {
		return x.Positives
	}
	return nil
}

func (x *ScoreBreakdown) GetNegatives() []string {
	if x != nil {
		return x.Negatives
	}
	return nil
}

// Submission is one benchmarked architecture.
type Submission struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChallengeSlug    string                 `protobuf:"bytes,2,opt,name=challenge_slug,json=challengeSlug,proto3" json:"challenge_slug,omitempty"`
	ChallengeVersion int32                  `protobuf:"varint,3,opt,name=challenge_version,json=challengeVersion,proto3" json:"challenge_version,omitempty"`
	DisplayName      string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// status: completed | failed
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// score is 0 for a failed submission (which never ranks).
	Score float64 `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	// rank is derived from the leaderboard at read time (0 = unranked/failed).
	Rank      int64             `protobuf:"varint,7,opt,name=rank,proto3" json:"rank,omitempty"`
	Plan      *LoadPlan         `protobuf:"bytes,8,opt,name=plan,proto3" json:"plan,omitempty"`
	Metrics   *SystemMetrics    `protobuf:"bytes,9,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Diagnosis *Diagnosis        `protobuf:"bytes,10,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	Capacity  []*CapacityReport `protobuf:"bytes,11,rep,name=capacity,proto3" json:"capacity,omitempty"`
	Cost      *CostEstimate     `protobuf:"bytes,12,opt,name=cost,proto3" json:"cost,omitempty"`
	Breakdown *ScoreBreakdown   `protobuf:"bytes,13,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	Seed      uint64            `protobuf:"varint,14,opt,name=seed,proto3" json:"seed,omitempty"`
	// error explains a failed benchmark; empty otherwise.
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_loadline_v1_arena_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{15}
}

func (x *Submission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Submission) GetChallengeSlug() string {
	if x != nil {
		return x.ChallengeSlug
	}
	return ""
}

func (x *Submission) GetChallengeVersion() int32 {
	if x != nil {
		return x.ChallengeVersion
	}
	return 0
}

func (x *Submission) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Submission) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Submission) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Submission) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Submission) GetPlan() *LoadPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *Submission) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Submission) GetDiagnosis() *Diagnosis {
	if x != nil {
		return x.Diagnosis
	}
	return nil
}

func (x *Submission) GetCapacity() []*CapacityReport {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *Submission) GetCost() *CostEstimate {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Submission) GetBreakdown() *ScoreBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *Submission) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *Submission) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Submission) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

type SubmitChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *Submission            `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitChallengeResponse) Reset() {
	*x = SubmitChallengeResponse{}
	mi := &file_loadline_v1_arena_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitChallengeResponse) ProtoMessage() {}

func (x *SubmitChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitChallengeResponse.ProtoReflect.Descriptor instead.
func (*SubmitChallengeResponse) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitChallengeResponse) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type GetChallengeSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeSubmissionRequest) Reset() {
	*x = GetChallengeSubmissionRequest{}
	mi := &file_loadline_v1_arena_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeSubmissionRequest) ProtoMessage() {}

func (x *GetChallengeSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeSubmissionRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{17}
}

func (x *GetChallengeSubmissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetChallengeSubmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *Submission            `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeSubmissionResponse) Reset() {
	*x = GetChallengeSubmissionResponse{}
	mi := &file_loadline_v1_arena_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeSubmissionResponse) ProtoMessage() {}

func (x *GetChallengeSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeSubmissionResponse.ProtoReflect.Descriptor instead.
func (*GetChallengeSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{18}
}

func (x *GetChallengeSubmissionResponse) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

// LeaderboardEntry is one ranked submission. Only public benchmark data is
// exposed: there is no identity beyond the display name.
type LeaderboardEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rank           int64                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	SubmissionId   string                 `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Score          float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	ThroughputRps  float64                `protobuf:"fixed64,5,opt,name=throughput_rps,json=throughputRps,proto3" json:"throughput_rps,omitempty"`
	P95Ms          float64                `protobuf:"fixed64,6,opt,name=p95_ms,json=p95Ms,proto3" json:"p95_ms,omitempty"`
	P99Ms          float64                `protobuf:"fixed64,7,opt,name=p99_ms,json=p99Ms,proto3" json:"p99_ms,omitempty"`
	ErrorRate      float64                `protobuf:"fixed64,8,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	MonthlyCostUsd float64                `protobuf:"fixed64,9,opt,name=monthly_cost_usd,json=monthlyCostUsd,proto3" json:"monthly_cost_usd,omitempty"`
	CostKnown      bool                   `protobuf:"varint,10,opt,name=cost_known,json=costKnown,proto3" json:"cost_known,omitempty"`
	SubmittedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_loadline_v1_arena_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{19}
}

func (x *LeaderboardEntry) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *LeaderboardEntry) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetThroughputRps() float64 {
	if x != nil {
		return x.ThroughputRps
	}
	return 0
}

func (x *LeaderboardEntry) GetP95Ms() float64 {
	if x != nil {
		return x.P95Ms
	}
	return 0
}

func (x *LeaderboardEntry) GetP99Ms() float64 {
	if x != nil {
		return x.P99Ms
	}
	return 0
}

func (x *LeaderboardEntry) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *LeaderboardEntry) GetMonthlyCostUsd() float64 {
	if x != nil {
		return x.MonthlyCostUsd
	}
	return 0
}

func (x *LeaderboardEntry) GetCostKnown() bool {
	if x != nil {
		return x.CostKnown
	}
	return false
}

func (x *LeaderboardEntry) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

type GetChallengeLeaderboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Slug  string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	// version is the challenge version whose leaderboard is requested; 0 means
	// the challenge's current version. Historical versions keep their own
	// leaderboards, so an edited challenge never rewrites past results.
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// limit caps the rows returned; 0 uses the server default.
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// recent orders by submission time (newest first) instead of score.
	Recent        bool `protobuf:"varint,4,opt,name=recent,proto3" json:"recent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeLeaderboardRequest) Reset() {
	*x = GetChallengeLeaderboardRequest{}
	mi := &file_loadline_v1_arena_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeLeaderboardRequest) ProtoMessage() {}

func (x *GetChallengeLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{20}
}

func (x *GetChallengeLeaderboardRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetChallengeLeaderboardRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetChallengeLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChallengeLeaderboardRequest) GetRecent() bool {
	if x != nil {
		return x.Recent
	}
	return false
}

type GetChallengeLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeLeaderboardResponse) Reset() {
	*x = GetChallengeLeaderboardResponse{}
	mi := &file_loadline_v1_arena_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeLeaderboardResponse) ProtoMessage() {}

func (x *GetChallengeLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loadline_v1_arena_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetChallengeLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_loadline_v1_arena_proto_rawDescGZIP(), []int{21}
}

func (x *GetChallengeLeaderboardResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetChallengeLeaderboardResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetChallengeLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_loadline_v1_arena_proto protoreflect.FileDescriptor

const file_loadline_v1_arena_proto_rawDesc = "" +
	"\n" +
	"\x17loadline/v1/arena.proto\x12\vloadline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cloadline/v1/simulation.proto\"\xec\x01\n" +
	"\x14ChallengeConstraints\x122\n" +
	"\x15target_throughput_rps\x18\x01 \x01(\x01R\x13targetThroughputRps\x12\"\n" +
	"\rtarget_p95_ms\x18\x02 \x01(\x01R\vtargetP95Ms\x12\"\n" +
	"\rtarget_p99_ms\x18\x03 \x01(\x01R\vtargetP99Ms\x12*\n" +
	"\x11target_error_rate\x18\x04 \x01(\x01R\x0ftargetErrorRate\x12,\n" +
	"\x12monthly_budget_usd\x18\x05 \x01(\x01R\x10monthlyBudgetUsd\"\x98\x02\n" +
	"\x0fFailureScenario\x12\x1f\n" +
	"\vtarget_kind\x18\x01 \x01(\tR\n" +
	"targetKind\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\bstart_ms\x18\x03 \x01(\x01R\astartMs\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x01R\n" +
	"durationMs\x12(\n" +
	"\x10added_latency_ms\x18\x05 \x01(\x01R\x0eaddedLatencyMs\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x06 \x01(\x01R\terrorRate\x12(\n" +
	"\x10packet_loss_rate\x18\a \x01(\x01R\x0epacketLossRate\x12!\n" +
	"\fpass_through\x18\b \x01(\bR\vpassThrough\"7\n" +
	"\x0fKindRequirement\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x05R\x03min\"\xab\x01\n" +
	"\x0eScoringWeights\x12\x1e\n" +
	"\n" +
	"throughput\x18\x01 \x01(\x01R\n" +
	"throughput\x12\x18\n" +
	"\alatency\x18\x02 \x01(\x01R\alatency\x12 \n" +
	"\vreliability\x18\x03 \x01(\x01R\vreliability\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x01R\x04cost\x12)\n" +
	"\x10failure_recovery\x18\x05 \x01(\x01R\x0ffailureRecovery\"O\n" +
	"\x13FailureScenarioList\x128\n" +
	"\bfailures\x18\x01 \x03(\v2\x1c.loadline.v1.FailureScenarioR\bfailures\"W\n" +
	"\x13KindRequirementList\x12@\n" +
	"\frequirements\x18\x01 \x03(\v2\x1c.loadline.v1.KindRequirementR\frequirements\"\x80\x03\n" +
	"\x10ChallengeSummary\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x125\n" +
	"\bworkload\x18\b \x01(\v2\x19.loadline.v1.WorkloadSpecR\bworkload\x12C\n" +
	"\vconstraints\x18\t \x01(\v2!.loadline.v1.ChallengeConstraintsR\vconstraints\x128\n" +
	"\bfailures\x18\n" +
	" \x03(\v2\x1c.loadline.v1.FailureScenarioR\bfailures\"\xf2\x01\n" +
	"\tChallenge\x127\n" +
	"\asummary\x18\x01 \x01(\v2\x1d.loadline.v1.ChallengeSummaryR\asummary\x12@\n" +
	"\frequirements\x18\x02 \x03(\v2\x1c.loadline.v1.KindRequirementR\frequirements\x125\n" +
	"\ascoring\x18\x03 \x01(\v2\x1b.loadline.v1.ScoringWeightsR\ascoring\x12\x12\n" +
	"\x04seed\x18\x04 \x01(\x04R\x04seed\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x01R\n" +
	"durationMs\"\x17\n" +
	"\x15ListChallengesRequest\"W\n" +
	"\x16ListChallengesResponse\x12=\n" +
	"\n" +
	"challenges\x18\x01 \x03(\v2\x1d.loadline.v1.ChallengeSummaryR\n" +
	"challenges\")\n" +
	"\x13GetChallengeRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"L\n" +
	"\x14GetChallengeResponse\x124\n" +
	"\tchallenge\x18\x01 \x01(\v2\x16.loadline.v1.ChallengeR\tchallenge\"\x9a\x01\n" +
	"\x16SubmitChallengeRequest\x12%\n" +
	"\x0echallenge_slug\x18\x01 \x01(\tR\rchallengeSlug\x126\n" +
	"\x17architecture_version_id\x18\x02 \x01(\tR\x15architectureVersionId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"\xa2\x01\n" +
	"\x0eScoreComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x1a\n" +
	"\bweighted\x18\x04 \x01(\x01R\bweighted\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\x12\x1a\n" +
	"\bevidence\x18\x06 \x03(\tR\bevidence\"\x9f\x01\n" +
	"\x0eScoreBreakdown\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12;\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x1b.loadline.v1.ScoreComponentR\n" +
	"components\x12\x1c\n" +
	"\tpositives\x18\x03 \x03(\tR\tpositives\x12\x1c\n" +
	"\tnegatives\x18\x04 \x03(\tR\tnegatives\"\xf8\x04\n" +
	"\n" +
	"Submission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0echallenge_slug\x18\x02 \x01(\tR\rchallengeSlug\x12+\n" +
	"\x11challenge_version\x18\x03 \x01(\x05R\x10challengeVersion\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\x12\x12\n" +
	"\x04rank\x18\a \x01(\x03R\x04rank\x12)\n" +
	"\x04plan\x18\b \x01(\v2\x15.loadline.v1.LoadPlanR\x04plan\x124\n" +
	"\ametrics\x18\t \x01(\v2\x1a.loadline.v1.SystemMetricsR\ametrics\x124\n" +
	"\tdiagnosis\x18\n" +
	" \x01(\v2\x16.loadline.v1.DiagnosisR\tdiagnosis\x127\n" +
	"\bcapacity\x18\v \x03(\v2\x1b.loadline.v1.CapacityReportR\bcapacity\x12-\n" +
	"\x04cost\x18\f \x01(\v2\x19.loadline.v1.CostEstimateR\x04cost\x129\n" +
	"\tbreakdown\x18\r \x01(\v2\x1b.loadline.v1.ScoreBreakdownR\tbreakdown\x12\x12\n" +
	"\x04seed\x18\x0e \x01(\x04R\x04seed\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x12=\n" +
	"\fsubmitted_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\"R\n" +
	"\x17SubmitChallengeResponse\x127\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x17.loadline.v1.SubmissionR\n" +
	"submission\"/\n" +
	"\x1dGetChallengeSubmissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x1eGetChallengeSubmissionResponse\x127\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x17.loadline.v1.SubmissionR\n" +
	"submission\"\x80\x03\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x03R\x04rank\x12#\n" +
	"\rsubmission_id\x18\x02 \x01(\tR\fsubmissionId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12%\n" +
	"\x0ethroughput_rps\x18\x05 \x01(\x01R\rthroughputRps\x12\x15\n" +
	"\x06p95_ms\x18\x06 \x01(\x01R\x05p95Ms\x12\x15\n" +
	"\x06p99_ms\x18\a \x01(\x01R\x05p99Ms\x12\x1d\n" +
	"\n" +
	"error_rate\x18\b \x01(\x01R\terrorRate\x12(\n" +
	"\x10monthly_cost_usd\x18\t \x01(\x01R\x0emonthlyCostUsd\x12\x1d\n" +
	"\n" +
	"cost_known\x18\n" +
	" \x01(\bR\tcostKnown\x12=\n" +
	"\fsubmitted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\"|\n" +
	"\x1eGetChallengeLeaderboardRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06recent\x18\x04 \x01(\bR\x06recent\"\x88\x01\n" +
	"\x1fGetChallengeLeaderboardResponse\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x127\n" +
	"\aentries\x18\x03 \x03(\v2\x1d.loadline.v1.LeaderboardEntryR\aentries2\x85\x04\n" +
	"\fArenaService\x12Y\n" +
	"\x0eListChallenges\x12\".loadline.v1.ListChallengesRequest\x1a#.loadline.v1.ListChallengesResponse\x12S\n" +
	"\fGetChallenge\x12 .loadline.v1.GetChallengeRequest\x1a!.loadline.v1.GetChallengeResponse\x12\\\n" +
	"\x0fSubmitChallenge\x12#.loadline.v1.SubmitChallengeRequest\x1a$.loadline.v1.SubmitChallengeResponse\x12q\n" +
	"\x16GetChallengeSubmission\x12*.loadline.v1.GetChallengeSubmissionRequest\x1a+.loadline.v1.GetChallengeSubmissionResponse\x12t\n" +
	"\x17GetChallengeLeaderboard\x12+.loadline.v1.GetChallengeLeaderboardRequest\x1a,.loadline.v1.GetChallengeLeaderboardResponseBDZBgithub.com/kekubhai/Loadline/apps/simulator/loadline/v1;loadlinev1b\x06proto3"

var (
	file_loadline_v1_arena_proto_rawDescOnce sync.Once
	file_loadline_v1_arena_proto_rawDescData []byte
)

func file_loadline_v1_arena_proto_rawDescGZIP() []byte {
	file_loadline_v1_arena_proto_rawDescOnce.Do(func() {
		file_loadline_v1_arena_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loadline_v1_arena_proto_rawDesc), len(file_loadline_v1_arena_proto_rawDesc)))
	})
	return file_loadline_v1_arena_proto_rawDescData
}

var file_loadline_v1_arena_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_loadline_v1_arena_proto_goTypes = []any{
	(*ChallengeConstraints)(nil),            // 0: loadline.v1.ChallengeConstraints
	(*FailureScenario)(nil),                 // 1: loadline.v1.FailureScenario
	(*KindRequirement)(nil),                 // 2: loadline.v1.KindRequirement
	(*ScoringWeights)(nil),                  // 3: loadline.v1.ScoringWeights
	(*FailureScenarioList)(nil),             // 4: loadline.v1.FailureScenarioList
	(*KindRequirementList)(nil),             // 5: loadline.v1.KindRequirementList
	(*ChallengeSummary)(nil),                // 6: loadline.v1.ChallengeSummary
	(*Challenge)(nil),                       // 7: loadline.v1.Challenge
	(*ListChallengesRequest)(nil),           // 8: loadline.v1.ListChallengesRequest
	(*ListChallengesResponse)(nil),          // 9: loadline.v1.ListChallengesResponse
	(*GetChallengeRequest)(nil),             // 10: loadline.v1.GetChallengeRequest
	(*GetChallengeResponse)(nil),            // 11: loadline.v1.GetChallengeResponse
	(*SubmitChallengeRequest)(nil),          // 12: loadline.v1.SubmitChallengeRequest
	(*ScoreComponent)(nil),                  // 13: loadline.v1.ScoreComponent
	(*ScoreBreakdown)(nil),                  // 14: loadline.v1.ScoreBreakdown
	(*Submission)(nil),                      // 15: loadline.v1.Submission
	(*SubmitChallengeResponse)(nil),         // 16: loadline.v1.SubmitChallengeResponse
	(*GetChallengeSubmissionRequest)(nil),   // 17: loadline.v1.GetChallengeSubmissionRequest
	(*GetChallengeSubmissionResponse)(nil),  // 18: loadline.v1.GetChallengeSubmissionResponse
	(*LeaderboardEntry)(nil),                // 19: loadline.v1.LeaderboardEntry
	(*GetChallengeLeaderboardRequest)(nil),  // 20: loadline.v1.GetChallengeLeaderboardRequest
	(*GetChallengeLeaderboardResponse)(nil), // 21: loadline.v1.GetChallengeLeaderboardResponse
	(*WorkloadSpec)(nil),                    // 22: loadline.v1.WorkloadSpec
	(*LoadPlan)(nil),                        // 23: loadline.v1.LoadPlan
	(*SystemMetrics)(nil),                   // 24: loadline.v1.SystemMetrics
	(*Diagnosis)(nil),                       // 25: loadline.v1.Diagnosis
	(*CapacityReport)(nil),                  // 26: loadline.v1.CapacityReport
	(*CostEstimate)(nil),                    // 27: loadline.v1.CostEstimate
	(*timestamppb.Timestamp)(nil),           // 28: google.protobuf.Timestamp
}
var file_loadline_v1_arena_proto_depIdxs = []int32{
	1,  // 0: loadline.v1.FailureScenarioList.failures:type_name -> loadline.v1.FailureScenario
	2,  // 1: loadline.v1.KindRequirementList.requirements:type_name -> loadline.v1.KindRequirement
	22, // 2: loadline.v1.ChallengeSummary.workload:type_name -> loadline.v1.WorkloadSpec
	0,  // 3: loadline.v1.ChallengeSummary.constraints:type_name -> loadline.v1.ChallengeConstraints
	1,  // 4: loadline.v1.ChallengeSummary.failures:type_name -> loadline.v1.FailureScenario
	6,  // 5: loadline.v1.Challenge.summary:type_name -> loadline.v1.ChallengeSummary
	2,  // 6: loadline.v1.Challenge.requirements:type_name -> loadline.v1.KindRequirement
	3,  // 7: loadline.v1.Challenge.scoring:type_name -> loadline.v1.ScoringWeights
	6,  // 8: loadline.v1.ListChallengesResponse.challenges:type_name -> loadline.v1.ChallengeSummary
	7,  // 9: loadline.v1.GetChallengeResponse.challenge:type_name -> loadline.v1.Challenge
	13, // 10: loadline.v1.ScoreBreakdown.components:type_name -> loadline.v1.ScoreComponent
	23, // 11: loadline.v1.Submission.plan:type_name -> loadline.v1.LoadPlan
	24, // 12: loadline.v1.Submission.metrics:type_name -> loadline.v1.SystemMetrics
	25, // 13: loadline.v1.Submission.diagnosis:type_name -> loadline.v1.Diagnosis
	26, // 14: loadline.v1.Submission.capacity:type_name -> loadline.v1.CapacityReport
	27, // 15: loadline.v1.Submission.cost:type_name -> loadline.v1.CostEstimate
	14, // 16: loadline.v1.Submission.breakdown:type_name -> loadline.v1.ScoreBreakdown
	28, // 17: loadline.v1.Submission.submitted_at:type_name -> google.protobuf.Timestamp
	15, // 18: loadline.v1.SubmitChallengeResponse.submission:type_name -> loadline.v1.Submission
	15, // 19: loadline.v1.GetChallengeSubmissionResponse.submission:type_name -> loadline.v1.Submission
	28, // 20: loadline.v1.LeaderboardEntry.submitted_at:type_name -> google.protobuf.Timestamp
	19, // 21: loadline.v1.GetChallengeLeaderboardResponse.entries:type_name -> loadline.v1.LeaderboardEntry
	8,  // 22: loadline.v1.ArenaService.ListChallenges:input_type -> loadline.v1.ListChallengesRequest
	10, // 23: loadline.v1.ArenaService.GetChallenge:input_type -> loadline.v1.GetChallengeRequest
	12, // 24: loadline.v1.ArenaService.SubmitChallenge:input_type -> loadline.v1.SubmitChallengeRequest
	17, // 25: loadline.v1.ArenaService.GetChallengeSubmission:input_type -> loadline.v1.GetChallengeSubmissionRequest
	20, // 26: loadline.v1.ArenaService.GetChallengeLeaderboard:input_type -> loadline.v1.GetChallengeLeaderboardRequest
	9,  // 27: loadline.v1.ArenaService.ListChallenges:output_type -> loadline.v1.ListChallengesResponse
	11, // 28: loadline.v1.ArenaService.GetChallenge:output_type -> loadline.v1.GetChallengeResponse
	16, // 29: loadline.v1.ArenaService.SubmitChallenge:output_type -> loadline.v1.SubmitChallengeResponse
	18, // 30: loadline.v1.ArenaService.GetChallengeSubmission:output_type -> loadline.v1.GetChallengeSubmissionResponse
	21, // 31: loadline.v1.ArenaService.GetChallengeLeaderboard:output_type -> loadline.v1.GetChallengeLeaderboardResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_loadline_v1_arena_proto_init() }
func file_loadline_v1_arena_proto_init() {
	if File_loadline_v1_arena_proto != nil {
		return
	}
	file_loadline_v1_simulation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loadline_v1_arena_proto_rawDesc), len(file_loadline_v1_arena_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loadline_v1_arena_proto_goTypes,
		DependencyIndexes: file_loadline_v1_arena_proto_depIdxs,
		MessageInfos:      file_loadline_v1_arena_proto_msgTypes,
	}.Build()
	File_loadline_v1_arena_proto = out.File
	file_loadline_v1_arena_proto_goTypes = nil
	file_loadline_v1_arena_proto_depIdxs = nil
}
