// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: loadline/v1/arena.proto

package loadlinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArenaService_ListChallenges_FullMethodName          = "/loadline.v1.ArenaService/ListChallenges"
	ArenaService_GetChallenge_FullMethodName            = "/loadline.v1.ArenaService/GetChallenge"
	ArenaService_SubmitChallenge_FullMethodName         = "/loadline.v1.ArenaService/SubmitChallenge"
	ArenaService_GetChallengeSubmission_FullMethodName  = "/loadline.v1.ArenaService/GetChallengeSubmission"
	ArenaService_GetChallengeLeaderboard_FullMethodName = "/loadline.v1.ArenaService/GetChallengeLeaderboard"
)

// ArenaServiceClient is the client API for ArenaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArenaService is LOADLINE's benchmark API. It reuses the same simulation
// engine as SimulationService and WorkspaceService; it owns no simulation
// behavior, only benchmark orchestration and scoring.
type ArenaServiceClient interface {
	// List every embedded challenge.
	ListChallenges(ctx context.Context, in *ListChallengesRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error)
	// Fetch one challenge with its full evaluation rules.
	GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*GetChallengeResponse, error)
	// Benchmark a stored architecture version against a challenge.
	SubmitChallenge(ctx context.Context, in *SubmitChallengeRequest, opts ...grpc.CallOption) (*SubmitChallengeResponse, error)
	// Fetch one submission by id.
	GetChallengeSubmission(ctx context.Context, in *GetChallengeSubmissionRequest, opts ...grpc.CallOption) (*GetChallengeSubmissionResponse, error)
	// Fetch a challenge's leaderboard (score-ranked, or most recent).
	GetChallengeLeaderboard(ctx context.Context, in *GetChallengeLeaderboardRequest, opts ...grpc.CallOption) (*GetChallengeLeaderboardResponse, error)
}

type arenaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArenaServiceClient(cc grpc.ClientConnInterface) ArenaServiceClient {
	return &arenaServiceClient{cc}
}

func (c *arenaServiceClient) ListChallenges(ctx context.Context, in *ListChallengesRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChallengesResponse)
	err := c.cc.Invoke(ctx, ArenaService_ListChallenges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*GetChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChallengeResponse)
	err := c.cc.Invoke(ctx, ArenaService_GetChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) SubmitChallenge(ctx context.Context, in *SubmitChallengeRequest, opts ...grpc.CallOption) (*SubmitChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitChallengeResponse)
	err := c.cc.Invoke(ctx, ArenaService_SubmitChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) GetChallengeSubmission(ctx context.Context, in *GetChallengeSubmissionRequest, opts ...grpc.CallOption) (*GetChallengeSubmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChallengeSubmissionResponse)
	err := c.cc.Invoke(ctx, ArenaService_GetChallengeSubmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) GetChallengeLeaderboard(ctx context.Context, in *GetChallengeLeaderboardRequest, opts ...grpc.CallOption) (*GetChallengeLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChallengeLeaderboardResponse)
	err := c.cc.Invoke(ctx, ArenaService_GetChallengeLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArenaServiceServer is the server API for ArenaService service.
// All implementations should embed UnimplementedArenaServiceServer
// for forward compatibility.
//
// ArenaService is LOADLINE's benchmark API. It reuses the same simulation
// engine as SimulationService and WorkspaceService; it owns no simulation
// behavior, only benchmark orchestration and scoring.
type ArenaServiceServer interface {
	// List every embedded challenge.
	ListChallenges(context.Context, *ListChallengesRequest) (*ListChallengesResponse, error)
	// Fetch one challenge with its full evaluation rules.
	GetChallenge(context.Context, *GetChallengeRequest) (*GetChallengeResponse, error)
	// Benchmark a stored architecture version against a challenge.
	SubmitChallenge(context.Context, *SubmitChallengeRequest) (*SubmitChallengeResponse, error)
	// Fetch one submission by id.
	GetChallengeSubmission(context.Context, *GetChallengeSubmissionRequest) (*GetChallengeSubmissionResponse, error)
	// Fetch a challenge's leaderboard (score-ranked, or most recent).
	GetChallengeLeaderboard(context.Context, *GetChallengeLeaderboardRequest) (*GetChallengeLeaderboardResponse, error)
}

// UnimplementedArenaServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArenaServiceServer struct{}

func (UnimplementedArenaServiceServer) ListChallenges(context.Context, *ListChallengesRequest) (*ListChallengesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChallenges not implemented")
}
func (UnimplementedArenaServiceServer) GetChallenge(context.Context, *GetChallengeRequest) (*GetChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChallenge not implemented")
}
func (UnimplementedArenaServiceServer) SubmitChallenge(context.Context, *SubmitChallengeRequest) (*SubmitChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitChallenge not implemented")
}
func (UnimplementedArenaServiceServer) GetChallengeSubmission(context.Context, *GetChallengeSubmissionRequest) (*GetChallengeSubmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChallengeSubmission not implemented")
}
func (UnimplementedArenaServiceServer) GetChallengeLeaderboard(context.Context, *GetChallengeLeaderboardRequest) (*GetChallengeLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChallengeLeaderboard not implemented")
}
func (UnimplementedArenaServiceServer) testEmbeddedByValue() {}

// UnsafeArenaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArenaServiceServer will
// result in compilation errors.
type UnsafeArenaServiceServer interface {
	mustEmbedUnimplementedArenaServiceServer()
}

func RegisterArenaServiceServer(s grpc.ServiceRegistrar, srv ArenaServiceServer) {
	// If the following call panics, it indicates UnimplementedArenaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArenaService_ServiceDesc, srv)
}

func _ArenaService_ListChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).ListChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_ListChallenges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).ListChallenges(ctx, req.(*ListChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_GetChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).GetChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_GetChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).GetChallenge(ctx, req.(*GetChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_SubmitChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).SubmitChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_SubmitChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).SubmitChallenge(ctx, req.(*SubmitChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_GetChallengeSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChallengeSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).GetChallengeSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_GetChallengeSubmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).GetChallengeSubmission(ctx, req.(*GetChallengeSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_GetChallengeLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChallengeLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).GetChallengeLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_GetChallengeLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).GetChallengeLeaderboard(ctx, req.(*GetChallengeLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArenaService_ServiceDesc is the grpc.ServiceDesc for ArenaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArenaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loadline.v1.ArenaService",
	HandlerType: (*ArenaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListChallenges",
			Handler:    _ArenaService_ListChallenges_Handler,
		},
		{
			MethodName: "GetChallenge",
			Handler:    _ArenaService_GetChallenge_Handler,
		},
		{
			MethodName: "SubmitChallenge",
			Handler:    _ArenaService_SubmitChallenge_Handler,
		},
		{
			MethodName: "GetChallengeSubmission",
			Handler:    _ArenaService_GetChallengeSubmission_Handler,
		},
		{
			MethodName: "GetChallengeLeaderboard",
			Handler:    _ArenaService_GetChallengeLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loadline/v1/arena.proto",
}
