// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: loadline/v1/simulation.proto

package loadlinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulationService_CreateSimulation_FullMethodName    = "/loadline.v1.SimulationService/CreateSimulation"
	SimulationService_RunSimulation_FullMethodName       = "/loadline.v1.SimulationService/RunSimulation"
	SimulationService_GetSimulationStatus_FullMethodName = "/loadline.v1.SimulationService/GetSimulationStatus"
	SimulationService_StreamMetrics_FullMethodName       = "/loadline.v1.SimulationService/StreamMetrics"
	SimulationService_GetResults_FullMethodName          = "/loadline.v1.SimulationService/GetResults"
	SimulationService_GetDiagnosis_FullMethodName        = "/loadline.v1.SimulationService/GetDiagnosis"
	SimulationService_GetCapacity_FullMethodName         = "/loadline.v1.SimulationService/GetCapacity"
	SimulationService_GetCostEstimate_FullMethodName     = "/loadline.v1.SimulationService/GetCostEstimate"
	SimulationService_ListCatalog_FullMethodName         = "/loadline.v1.SimulationService/ListCatalog"
)

// SimulationServiceClient is the client API for SimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SimulationService is LOADLINE's ConnectRPC API over the Go simulation
// engine. The engine stays independent: this layer adapts transport
// messages to sim/packages calls and owns run lifecycle + streaming.
type SimulationServiceClient interface {
	// Create a stored simulation (architecture + workload + options).
	CreateSimulation(ctx context.Context, in *CreateSimulationRequest, opts ...grpc.CallOption) (*CreateSimulationResponse, error)
	// Start asynchronous execution of a stored simulation.
	RunSimulation(ctx context.Context, in *RunSimulationRequest, opts ...grpc.CallOption) (*RunSimulationResponse, error)
	// Poll a simulation's status and latest progress snapshot.
	GetSimulationStatus(ctx context.Context, in *GetSimulationStatusRequest, opts ...grpc.CallOption) (*GetSimulationStatusResponse, error)
	// Stream progress snapshots while running, then status and final
	// results; the stream ends after the terminal frame.
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMetricsResponse], error)
	// Fetch final results of a completed run.
	GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error)
	// Fetch the bottleneck diagnosis (optionally vs a baseline run).
	GetDiagnosis(ctx context.Context, in *GetDiagnosisRequest, opts ...grpc.CallOption) (*GetDiagnosisResponse, error)
	// Fetch per-component capacity estimates.
	GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error)
	// Fetch the monthly cost estimate (ESTIMATE, not live billing).
	GetCostEstimate(ctx context.Context, in *GetCostEstimateRequest, opts ...grpc.CallOption) (*GetCostEstimateResponse, error)
	// List the built-in provider catalog.
	ListCatalog(ctx context.Context, in *ListCatalogRequest, opts ...grpc.CallOption) (*ListCatalogResponse, error)
}

type simulationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationServiceClient(cc grpc.ClientConnInterface) SimulationServiceClient {
	return &simulationServiceClient{cc}
}

func (c *simulationServiceClient) CreateSimulation(ctx context.Context, in *CreateSimulationRequest, opts ...grpc.CallOption) (*CreateSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSimulationResponse)
	err := c.cc.Invoke(ctx, SimulationService_CreateSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) RunSimulation(ctx context.Context, in *RunSimulationRequest, opts ...grpc.CallOption) (*RunSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSimulationResponse)
	err := c.cc.Invoke(ctx, SimulationService_RunSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) GetSimulationStatus(ctx context.Context, in *GetSimulationStatusRequest, opts ...grpc.CallOption) (*GetSimulationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimulationStatusResponse)
	err := c.cc.Invoke(ctx, SimulationService_GetSimulationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimulationService_ServiceDesc.Streams[0], SimulationService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, StreamMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationService_StreamMetricsClient = grpc.ServerStreamingClient[StreamMetricsResponse]

func (c *simulationServiceClient) GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResultsResponse)
	err := c.cc.Invoke(ctx, SimulationService_GetResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) GetDiagnosis(ctx context.Context, in *GetDiagnosisRequest, opts ...grpc.CallOption) (*GetDiagnosisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiagnosisResponse)
	err := c.cc.Invoke(ctx, SimulationService_GetDiagnosis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapacityResponse)
	err := c.cc.Invoke(ctx, SimulationService_GetCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) GetCostEstimate(ctx context.Context, in *GetCostEstimateRequest, opts ...grpc.CallOption) (*GetCostEstimateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCostEstimateResponse)
	err := c.cc.Invoke(ctx, SimulationService_GetCostEstimate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) ListCatalog(ctx context.Context, in *ListCatalogRequest, opts ...grpc.CallOption) (*ListCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCatalogResponse)
	err := c.cc.Invoke(ctx, SimulationService_ListCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationServiceServer is the server API for SimulationService service.
// All implementations should embed UnimplementedSimulationServiceServer
// for forward compatibility.
//
// SimulationService is LOADLINE's ConnectRPC API over the Go simulation
// engine. The engine stays independent: this layer adapts transport
// messages to sim/packages calls and owns run lifecycle + streaming.
type SimulationServiceServer interface {
	// Create a stored simulation (architecture + workload + options).
	CreateSimulation(context.Context, *CreateSimulationRequest) (*CreateSimulationResponse, error)
	// Start asynchronous execution of a stored simulation.
	RunSimulation(context.Context, *RunSimulationRequest) (*RunSimulationResponse, error)
	// Poll a simulation's status and latest progress snapshot.
	GetSimulationStatus(context.Context, *GetSimulationStatusRequest) (*GetSimulationStatusResponse, error)
	// Stream progress snapshots while running, then status and final
	// results; the stream ends after the terminal frame.
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[StreamMetricsResponse]) error
	// Fetch final results of a completed run.
	GetResults(context.Context, *GetResultsRequest) (*GetResultsResponse, error)
	// Fetch the bottleneck diagnosis (optionally vs a baseline run).
	GetDiagnosis(context.Context, *GetDiagnosisRequest) (*GetDiagnosisResponse, error)
	// Fetch per-component capacity estimates.
	GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error)
	// Fetch the monthly cost estimate (ESTIMATE, not live billing).
	GetCostEstimate(context.Context, *GetCostEstimateRequest) (*GetCostEstimateResponse, error)
	// List the built-in provider catalog.
	ListCatalog(context.Context, *ListCatalogRequest) (*ListCatalogResponse, error)
}

// UnimplementedSimulationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulationServiceServer struct{}

func (UnimplementedSimulationServiceServer) CreateSimulation(context.Context, *CreateSimulationRequest) (*CreateSimulationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSimulation not implemented")
}
func (UnimplementedSimulationServiceServer) RunSimulation(context.Context, *RunSimulationRequest) (*RunSimulationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSimulation not implemented")
}
func (UnimplementedSimulationServiceServer) GetSimulationStatus(context.Context, *GetSimulationStatusRequest) (*GetSimulationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSimulationStatus not implemented")
}
func (UnimplementedSimulationServiceServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[StreamMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedSimulationServiceServer) GetResults(context.Context, *GetResultsRequest) (*GetResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResults not implemented")
}
func (UnimplementedSimulationServiceServer) GetDiagnosis(context.Context, *GetDiagnosisRequest) (*GetDiagnosisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiagnosis not implemented")
}
func (UnimplementedSimulationServiceServer) GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapacity not implemented")
}
func (UnimplementedSimulationServiceServer) GetCostEstimate(context.Context, *GetCostEstimateRequest) (*GetCostEstimateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCostEstimate not implemented")
}
func (UnimplementedSimulationServiceServer) ListCatalog(context.Context, *ListCatalogRequest) (*ListCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCatalog not implemented")
}
func (UnimplementedSimulationServiceServer) testEmbeddedByValue() {}

// UnsafeSimulationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationServiceServer will
// result in compilation errors.
type UnsafeSimulationServiceServer interface {
	mustEmbedUnimplementedSimulationServiceServer()
}

func RegisterSimulationServiceServer(s grpc.ServiceRegistrar, srv SimulationServiceServer) {
	// If the following call panics, it indicates UnimplementedSimulationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulationService_ServiceDesc, srv)
}

func _SimulationService_CreateSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).CreateSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_CreateSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).CreateSimulation(ctx, req.(*CreateSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_RunSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).RunSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_RunSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).RunSimulation(ctx, req.(*RunSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_GetSimulationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimulationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetSimulationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_GetSimulationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetSimulationStatus(ctx, req.(*GetSimulationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulationServiceServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, StreamMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationService_StreamMetricsServer = grpc.ServerStreamingServer[StreamMetricsResponse]

func _SimulationService_GetResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_GetResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetResults(ctx, req.(*GetResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_GetDiagnosis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagnosisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetDiagnosis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_GetDiagnosis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetDiagnosis(ctx, req.(*GetDiagnosisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_GetCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_GetCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetCapacity(ctx, req.(*GetCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_GetCostEstimate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCostEstimateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetCostEstimate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_GetCostEstimate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetCostEstimate(ctx, req.(*GetCostEstimateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_ListCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).ListCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_ListCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).ListCatalog(ctx, req.(*ListCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulationService_ServiceDesc is the grpc.ServiceDesc for SimulationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loadline.v1.SimulationService",
	HandlerType: (*SimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSimulation",
			Handler:    _SimulationService_CreateSimulation_Handler,
		},
		{
			MethodName: "RunSimulation",
			Handler:    _SimulationService_RunSimulation_Handler,
		},
		{
			MethodName: "GetSimulationStatus",
			Handler:    _SimulationService_GetSimulationStatus_Handler,
		},
		{
			MethodName: "GetResults",
			Handler:    _SimulationService_GetResults_Handler,
		},
		{
			MethodName: "GetDiagnosis",
			Handler:    _SimulationService_GetDiagnosis_Handler,
		},
		{
			MethodName: "GetCapacity",
			Handler:    _SimulationService_GetCapacity_Handler,
		},
		{
			MethodName: "GetCostEstimate",
			Handler:    _SimulationService_GetCostEstimate_Handler,
		},
		{
			MethodName: "ListCatalog",
			Handler:    _SimulationService_ListCatalog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _SimulationService_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loadline/v1/simulation.proto",
}
