// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: loadline/v1/workspace.proto

package loadlinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceService_CreateProject_FullMethodName             = "/loadline.v1.WorkspaceService/CreateProject"
	WorkspaceService_GetProject_FullMethodName                = "/loadline.v1.WorkspaceService/GetProject"
	WorkspaceService_ListProjects_FullMethodName              = "/loadline.v1.WorkspaceService/ListProjects"
	WorkspaceService_UpdateProject_FullMethodName             = "/loadline.v1.WorkspaceService/UpdateProject"
	WorkspaceService_DeleteProject_FullMethodName             = "/loadline.v1.WorkspaceService/DeleteProject"
	WorkspaceService_CreateArchitecture_FullMethodName        = "/loadline.v1.WorkspaceService/CreateArchitecture"
	WorkspaceService_GetArchitecture_FullMethodName           = "/loadline.v1.WorkspaceService/GetArchitecture"
	WorkspaceService_ListArchitectures_FullMethodName         = "/loadline.v1.WorkspaceService/ListArchitectures"
	WorkspaceService_UpdateArchitecture_FullMethodName        = "/loadline.v1.WorkspaceService/UpdateArchitecture"
	WorkspaceService_DeleteArchitecture_FullMethodName        = "/loadline.v1.WorkspaceService/DeleteArchitecture"
	WorkspaceService_CreateArchitectureVersion_FullMethodName = "/loadline.v1.WorkspaceService/CreateArchitectureVersion"
	WorkspaceService_GetArchitectureVersion_FullMethodName    = "/loadline.v1.WorkspaceService/GetArchitectureVersion"
	WorkspaceService_ListArchitectureVersions_FullMethodName  = "/loadline.v1.WorkspaceService/ListArchitectureVersions"
	WorkspaceService_CreateWorkload_FullMethodName            = "/loadline.v1.WorkspaceService/CreateWorkload"
	WorkspaceService_GetWorkload_FullMethodName               = "/loadline.v1.WorkspaceService/GetWorkload"
	WorkspaceService_ListWorkloads_FullMethodName             = "/loadline.v1.WorkspaceService/ListWorkloads"
	WorkspaceService_UpdateWorkload_FullMethodName            = "/loadline.v1.WorkspaceService/UpdateWorkload"
	WorkspaceService_DeleteWorkload_FullMethodName            = "/loadline.v1.WorkspaceService/DeleteWorkload"
	WorkspaceService_ExecuteSimulation_FullMethodName         = "/loadline.v1.WorkspaceService/ExecuteSimulation"
	WorkspaceService_GetSimulationRun_FullMethodName          = "/loadline.v1.WorkspaceService/GetSimulationRun"
	WorkspaceService_ListSimulationRuns_FullMethodName        = "/loadline.v1.WorkspaceService/ListSimulationRuns"
)

// WorkspaceServiceClient is the client API for WorkspaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkspaceService persists LOADLINE workspaces and runs simulations against
// stored documents. It owns no simulation behavior: it loads an architecture
// version and a workload, hands them to the same in-memory engine
// SimulationService uses, and stores what the engine returned.
type WorkspaceServiceClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error)
	// --- Architectures ------------------------------------------------------
	// Create an architecture and its first version in one transaction.
	CreateArchitecture(ctx context.Context, in *CreateArchitectureRequest, opts ...grpc.CallOption) (*CreateArchitectureResponse, error)
	GetArchitecture(ctx context.Context, in *GetArchitectureRequest, opts ...grpc.CallOption) (*GetArchitectureResponse, error)
	ListArchitectures(ctx context.Context, in *ListArchitecturesRequest, opts ...grpc.CallOption) (*ListArchitecturesResponse, error)
	UpdateArchitecture(ctx context.Context, in *UpdateArchitectureRequest, opts ...grpc.CallOption) (*UpdateArchitectureResponse, error)
	DeleteArchitecture(ctx context.Context, in *DeleteArchitectureRequest, opts ...grpc.CallOption) (*DeleteArchitectureResponse, error)
	// --- Architecture versions (immutable) ----------------------------------
	CreateArchitectureVersion(ctx context.Context, in *CreateArchitectureVersionRequest, opts ...grpc.CallOption) (*CreateArchitectureVersionResponse, error)
	GetArchitectureVersion(ctx context.Context, in *GetArchitectureVersionRequest, opts ...grpc.CallOption) (*GetArchitectureVersionResponse, error)
	ListArchitectureVersions(ctx context.Context, in *ListArchitectureVersionsRequest, opts ...grpc.CallOption) (*ListArchitectureVersionsResponse, error)
	// --- Workloads ----------------------------------------------------------
	CreateWorkload(ctx context.Context, in *CreateWorkloadRequest, opts ...grpc.CallOption) (*CreateWorkloadResponse, error)
	GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetWorkloadResponse, error)
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error)
	UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*UpdateWorkloadResponse, error)
	DeleteWorkload(ctx context.Context, in *DeleteWorkloadRequest, opts ...grpc.CallOption) (*DeleteWorkloadResponse, error)
	// --- Simulation runs ----------------------------------------------------
	// Execute a stored version + workload on the simulation engine and persist
	// the run with its result summary in one transaction.
	ExecuteSimulation(ctx context.Context, in *ExecuteSimulationRequest, opts ...grpc.CallOption) (*ExecuteSimulationResponse, error)
	GetSimulationRun(ctx context.Context, in *GetSimulationRunRequest, opts ...grpc.CallOption) (*GetSimulationRunResponse, error)
	ListSimulationRuns(ctx context.Context, in *ListSimulationRunsRequest, opts ...grpc.CallOption) (*ListSimulationRunsResponse, error)
}

type workspaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceServiceClient(cc grpc.ClientConnInterface) WorkspaceServiceClient {
	return &workspaceServiceClient{cc}
}

func (c *workspaceServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProjectResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProjectResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) CreateArchitecture(ctx context.Context, in *CreateArchitectureRequest, opts ...grpc.CallOption) (*CreateArchitectureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArchitectureResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateArchitecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetArchitecture(ctx context.Context, in *GetArchitectureRequest, opts ...grpc.CallOption) (*GetArchitectureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArchitectureResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_GetArchitecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListArchitectures(ctx context.Context, in *ListArchitecturesRequest, opts ...grpc.CallOption) (*ListArchitecturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArchitecturesResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_ListArchitectures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) UpdateArchitecture(ctx context.Context, in *UpdateArchitectureRequest, opts ...grpc.CallOption) (*UpdateArchitectureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArchitectureResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_UpdateArchitecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) DeleteArchitecture(ctx context.Context, in *DeleteArchitectureRequest, opts ...grpc.CallOption) (*DeleteArchitectureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArchitectureResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_DeleteArchitecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) CreateArchitectureVersion(ctx context.Context, in *CreateArchitectureVersionRequest, opts ...grpc.CallOption) (*CreateArchitectureVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArchitectureVersionResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateArchitectureVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetArchitectureVersion(ctx context.Context, in *GetArchitectureVersionRequest, opts ...grpc.CallOption) (*GetArchitectureVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArchitectureVersionResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_GetArchitectureVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListArchitectureVersions(ctx context.Context, in *ListArchitectureVersionsRequest, opts ...grpc.CallOption) (*ListArchitectureVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArchitectureVersionsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_ListArchitectureVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) CreateWorkload(ctx context.Context, in *CreateWorkloadRequest, opts ...grpc.CallOption) (*CreateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkloadResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_CreateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkloadResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_GetWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*UpdateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkloadResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_UpdateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) DeleteWorkload(ctx context.Context, in *DeleteWorkloadRequest, opts ...grpc.CallOption) (*DeleteWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkloadResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_DeleteWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ExecuteSimulation(ctx context.Context, in *ExecuteSimulationRequest, opts ...grpc.CallOption) (*ExecuteSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSimulationResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_ExecuteSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetSimulationRun(ctx context.Context, in *GetSimulationRunRequest, opts ...grpc.CallOption) (*GetSimulationRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimulationRunResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_GetSimulationRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListSimulationRuns(ctx context.Context, in *ListSimulationRunsRequest, opts ...grpc.CallOption) (*ListSimulationRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSimulationRunsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_ListSimulationRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceServiceServer is the server API for WorkspaceService service.
// All implementations should embed UnimplementedWorkspaceServiceServer
// for forward compatibility.
//
// WorkspaceService persists LOADLINE workspaces and runs simulations against
// stored documents. It owns no simulation behavior: it loads an architecture
// version and a workload, hands them to the same in-memory engine
// SimulationService uses, and stores what the engine returned.
type WorkspaceServiceServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*UpdateProjectResponse, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error)
	// --- Architectures ------------------------------------------------------
	// Create an architecture and its first version in one transaction.
	CreateArchitecture(context.Context, *CreateArchitectureRequest) (*CreateArchitectureResponse, error)
	GetArchitecture(context.Context, *GetArchitectureRequest) (*GetArchitectureResponse, error)
	ListArchitectures(context.Context, *ListArchitecturesRequest) (*ListArchitecturesResponse, error)
	UpdateArchitecture(context.Context, *UpdateArchitectureRequest) (*UpdateArchitectureResponse, error)
	DeleteArchitecture(context.Context, *DeleteArchitectureRequest) (*DeleteArchitectureResponse, error)
	// --- Architecture versions (immutable) ----------------------------------
	CreateArchitectureVersion(context.Context, *CreateArchitectureVersionRequest) (*CreateArchitectureVersionResponse, error)
	GetArchitectureVersion(context.Context, *GetArchitectureVersionRequest) (*GetArchitectureVersionResponse, error)
	ListArchitectureVersions(context.Context, *ListArchitectureVersionsRequest) (*ListArchitectureVersionsResponse, error)
	// --- Workloads ----------------------------------------------------------
	CreateWorkload(context.Context, *CreateWorkloadRequest) (*CreateWorkloadResponse, error)
	GetWorkload(context.Context, *GetWorkloadRequest) (*GetWorkloadResponse, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error)
	UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*UpdateWorkloadResponse, error)
	DeleteWorkload(context.Context, *DeleteWorkloadRequest) (*DeleteWorkloadResponse, error)
	// --- Simulation runs ----------------------------------------------------
	// Execute a stored version + workload on the simulation engine and persist
	// the run with its result summary in one transaction.
	ExecuteSimulation(context.Context, *ExecuteSimulationRequest) (*ExecuteSimulationResponse, error)
	GetSimulationRun(context.Context, *GetSimulationRunRequest) (*GetSimulationRunResponse, error)
	ListSimulationRuns(context.Context, *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error)
}

// UnimplementedWorkspaceServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceServiceServer struct{}

func (UnimplementedWorkspaceServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedWorkspaceServiceServer) UpdateProject(context.Context, *UpdateProjectRequest) (*UpdateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedWorkspaceServiceServer) DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedWorkspaceServiceServer) CreateArchitecture(context.Context, *CreateArchitectureRequest) (*CreateArchitectureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArchitecture not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetArchitecture(context.Context, *GetArchitectureRequest) (*GetArchitectureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArchitecture not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListArchitectures(context.Context, *ListArchitecturesRequest) (*ListArchitecturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArchitectures not implemented")
}
func (UnimplementedWorkspaceServiceServer) UpdateArchitecture(context.Context, *UpdateArchitectureRequest) (*UpdateArchitectureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArchitecture not implemented")
}
func (UnimplementedWorkspaceServiceServer) DeleteArchitecture(context.Context, *DeleteArchitectureRequest) (*DeleteArchitectureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArchitecture not implemented")
}
func (UnimplementedWorkspaceServiceServer) CreateArchitectureVersion(context.Context, *CreateArchitectureVersionRequest) (*CreateArchitectureVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArchitectureVersion not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetArchitectureVersion(context.Context, *GetArchitectureVersionRequest) (*GetArchitectureVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArchitectureVersion not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListArchitectureVersions(context.Context, *ListArchitectureVersionsRequest) (*ListArchitectureVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArchitectureVersions not implemented")
}
func (UnimplementedWorkspaceServiceServer) CreateWorkload(context.Context, *CreateWorkloadRequest) (*CreateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkload not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetWorkload(context.Context, *GetWorkloadRequest) (*GetWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkload not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedWorkspaceServiceServer) UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*UpdateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkload not implemented")
}
func (UnimplementedWorkspaceServiceServer) DeleteWorkload(context.Context, *DeleteWorkloadRequest) (*DeleteWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkload not implemented")
}
func (UnimplementedWorkspaceServiceServer) ExecuteSimulation(context.Context, *ExecuteSimulationRequest) (*ExecuteSimulationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSimulation not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetSimulationRun(context.Context, *GetSimulationRunRequest) (*GetSimulationRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSimulationRun not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListSimulationRuns(context.Context, *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSimulationRuns not implemented")
}
func (UnimplementedWorkspaceServiceServer) testEmbeddedByValue() {}

// UnsafeWorkspaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceServiceServer will
// result in compilation errors.
type UnsafeWorkspaceServiceServer interface {
	mustEmbedUnimplementedWorkspaceServiceServer()
}

func RegisterWorkspaceServiceServer(s grpc.ServiceRegistrar, srv WorkspaceServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkspaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceService_ServiceDesc, srv)
}

func _WorkspaceService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_CreateArchitecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArchitectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateArchitecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateArchitecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateArchitecture(ctx, req.(*CreateArchitectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetArchitecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArchitectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetArchitecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetArchitecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetArchitecture(ctx, req.(*GetArchitectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListArchitectures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchitecturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListArchitectures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListArchitectures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListArchitectures(ctx, req.(*ListArchitecturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_UpdateArchitecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArchitectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).UpdateArchitecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_UpdateArchitecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).UpdateArchitecture(ctx, req.(*UpdateArchitectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_DeleteArchitecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArchitectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).DeleteArchitecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_DeleteArchitecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).DeleteArchitecture(ctx, req.(*DeleteArchitectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_CreateArchitectureVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArchitectureVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateArchitectureVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateArchitectureVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateArchitectureVersion(ctx, req.(*CreateArchitectureVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetArchitectureVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArchitectureVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetArchitectureVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetArchitectureVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetArchitectureVersion(ctx, req.(*GetArchitectureVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListArchitectureVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchitectureVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListArchitectureVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListArchitectureVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListArchitectureVersions(ctx, req.(*ListArchitectureVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_CreateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CreateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CreateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CreateWorkload(ctx, req.(*CreateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetWorkload(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListWorkloads(ctx, req.(*ListWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_UpdateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).UpdateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_UpdateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).UpdateWorkload(ctx, req.(*UpdateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_DeleteWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).DeleteWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_DeleteWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).DeleteWorkload(ctx, req.(*DeleteWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ExecuteSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ExecuteSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ExecuteSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ExecuteSimulation(ctx, req.(*ExecuteSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetSimulationRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimulationRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetSimulationRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetSimulationRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetSimulationRun(ctx, req.(*GetSimulationRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListSimulationRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSimulationRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ListSimulationRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ListSimulationRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ListSimulationRuns(ctx, req.(*ListSimulationRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceService_ServiceDesc is the grpc.ServiceDesc for WorkspaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loadline.v1.WorkspaceService",
	HandlerType: (*WorkspaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _WorkspaceService_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _WorkspaceService_GetProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _WorkspaceService_ListProjects_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _WorkspaceService_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _WorkspaceService_DeleteProject_Handler,
		},
		{
			MethodName: "CreateArchitecture",
			Handler:    _WorkspaceService_CreateArchitecture_Handler,
		},
		{
			MethodName: "GetArchitecture",
			Handler:    _WorkspaceService_GetArchitecture_Handler,
		},
		{
			MethodName: "ListArchitectures",
			Handler:    _WorkspaceService_ListArchitectures_Handler,
		},
		{
			MethodName: "UpdateArchitecture",
			Handler:    _WorkspaceService_UpdateArchitecture_Handler,
		},
		{
			MethodName: "DeleteArchitecture",
			Handler:    _WorkspaceService_DeleteArchitecture_Handler,
		},
		{
			MethodName: "CreateArchitectureVersion",
			Handler:    _WorkspaceService_CreateArchitectureVersion_Handler,
		},
		{
			MethodName: "GetArchitectureVersion",
			Handler:    _WorkspaceService_GetArchitectureVersion_Handler,
		},
		{
			MethodName: "ListArchitectureVersions",
			Handler:    _WorkspaceService_ListArchitectureVersions_Handler,
		},
		{
			MethodName: "CreateWorkload",
			Handler:    _WorkspaceService_CreateWorkload_Handler,
		},
		{
			MethodName: "GetWorkload",
			Handler:    _WorkspaceService_GetWorkload_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _WorkspaceService_ListWorkloads_Handler,
		},
		{
			MethodName: "UpdateWorkload",
			Handler:    _WorkspaceService_UpdateWorkload_Handler,
		},
		{
			MethodName: "DeleteWorkload",
			Handler:    _WorkspaceService_DeleteWorkload_Handler,
		},
		{
			MethodName: "ExecuteSimulation",
			Handler:    _WorkspaceService_ExecuteSimulation_Handler,
		},
		{
			MethodName: "GetSimulationRun",
			Handler:    _WorkspaceService_GetSimulationRun_Handler,
		},
		{
			MethodName: "ListSimulationRuns",
			Handler:    _WorkspaceService_ListSimulationRuns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loadline/v1/workspace.proto",
}
